+ JOB=10
+ NO_JOBS=16
+ [[ ! -n 10 ]]
+ [[ ! -n 16 ]]
+ [[ 10 == global ]]
+ set +x
+ pkgcheck -r gentoo --reporter FancyReporter 'media-sound/*' 'sys-fs/*' 'www-apps/*' 'x11-drivers/*' 'games-puzzle/*' 'sys-process/*' 'gnustep-apps/*' 'x11-proto/*' 'x11-base/*' 'games-sports/*' -d imlate -d unstable_only -d cleanup -d stale_unstable -d UnusedGlobalFlags -d UnusedLicense --profile-disable-dev --profile-disable-exp
WARNING pkgcore: invalid glsa- glsa-201206-24.xml, package www-servers/tomcat:
               : error range rlt version 5.5.34 is a guaranteed empty set

media-sound/SmarTagger
  DeprecatedEAPI: version 0.1-r1: uses deprecated EAPI: 0
  MissingChksum: version 0.1-r1: "SmarTagger-0.1.tar.gz" missing required chksums: sha512, whirlpool; has chksums: sha256, size

media-sound/a2jmidid
  DeprecatedEclass: version 8: uses deprecated eclass(es): [ python (migrate to python-r1 / python-single-r1 / python-any-r1) ]

media-sound/aacplusenc
  MissingChksum: version 0.17.5: "aacplusenc_0.17.5.tar.gz" missing required chksums: sha512, whirlpool; has chksums: rmd160, sha1, sha256, size

media-sound/abcde
  DroppedKeywordWarning: version 2.6: keywords dropped: ppc
  DroppedKeywordWarning: version 2.7: keywords dropped: ppc64

media-sound/adplay
  MissingChksum: version 1.7: "adplay-1.7.tar.bz2" missing required chksums: sha512, whirlpool; has chksums: sha256, size

media-sound/aeolus
  DeprecatedEAPI: version 0.8.1: uses deprecated EAPI: 0
  DeprecatedEAPI: version 0.8.4: uses deprecated EAPI: 0
  DroppedKeywordWarning: version 0.9.0: keywords dropped: x86
  MissingChksum: version 0.8.1: "aeolus-0.8.1.tar.bz2" missing required chksums: sha512, whirlpool; has chksums: sha256, size

media-sound/alac_decoder
  DeprecatedEAPI: version 0.1.3: uses deprecated EAPI: 2
  DeprecatedEAPI: version 0.2.0: uses deprecated EAPI: 2
  MissingChksum: version 0.1.3: "alac_decoder-0.1.3.tar.gz" missing required chksums: sha512, whirlpool; has chksums: sha256, size
  MissingChksum: version 0.2.0: "alac_decoder-0.2.0.tgz" missing required chksums: sha512, whirlpool; has chksums: sha256, size

media-sound/alsamixer-app
  DeprecatedEAPI: version 0.1: uses deprecated EAPI: 0
  MissingChksum: version 0.1: "AlsaMixer.app-0.1.tar.gz" missing required chksums: sha512, whirlpool; has chksums: rmd160, sha1, sha256, size
ERROR pkgcore: caught unexpected exception accessing keywords from ebuild src:
             : sys-devel/gettext-0.19.4, exception Metadata Exception: pkg
             : ebuild src: sys-devel/gettext-0.19.4, attr keywords
ERROR pkgcore: error: Metadata Exception: pkg ebuild src:
             : sys-devel/gettext-0.19.4, attr data
ERROR pkgcore: error: bytes_ro_StringIO instance has no attribute '__len__'
ERROR pkgcore: None
ERROR root: check <pkgcheck.visibility.VisibilityReport object at
          : 0x7f138167b250> raised
ERROR root: Traceback (most recent call last):
ERROR root:   File "/usr/lib64/python2.7/site-packages/pkgcheck/base.py", line
          : 337, in feed
ERROR root:     check.feed(item, reporter)
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcheck/visibility.py", line
          : 264, in feed
ERROR root:     self.process_depset(pkg, attr, edepset, profiles, reporter)
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcheck/visibility.py", line
          : 315, in process_depset
ERROR root:     if any(True for pkg in src if visible(pkg)):
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcheck/visibility.py", line
          : 315, in <genexpr>
ERROR root:     if any(True for pkg in src if visible(pkg)):
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/restrictions/boolean.py
          : ", line 247, in match
ERROR root:     if not rest.match(vals):
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/package/base.py", line
          : 101, in dynamic_getattr_dict
ERROR root:     raise_from(MetadataException(self, attr, str(e)))
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/package/base.py", line
          : 93, in dynamic_getattr_dict
ERROR root:     val = functor(self)
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/ebuild/ebuild_src.py",
          : line 207, in <lambda>
ERROR root:     s.data.pop("KEYWORDS", "").split()))
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/package/base.py", line
          : 103, in dynamic_getattr_dict
ERROR root:     raise_from(MetadataException(self, attr, str(e)))
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/package/base.py", line
          : 93, in dynamic_getattr_dict
ERROR root:     val = functor(self)
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/package/metadata.py",
          : line 59, in _get_data
ERROR root:     return self._fetch_metadata()
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/ebuild/ebuild_src.py",
          : line 274, in _fetch_metadata
ERROR root:     return self._parent._get_metadata(self, ebp=ebp,
          : force_regen=force_regen)
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/ebuild/ebuild_src.py",
          : line 365, in _get_metadata
ERROR root:     return self._update_metadata(pkg, ebp=ebp)
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/ebuild/ebuild_src.py",
          : line 373, in _update_metadata
ERROR root:     mydata = my_proc.get_keys(pkg, self._ecache)
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/ebuild/processor.py",
          : line 835, in get_keys
ERROR root:     {"key": receive_key})
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/ebuild/processor.py",
          : line 768, in _run_depend_like_phase
ERROR root:     self.write("%s %i\n%s" % (command, len(data), data),
          : append_newline=False)
ERROR root: MetadataException: Metadata Exception: pkg ebuild src:
          : sys-devel/gettext-0.19.4, attr keywords
ERROR root: error: Metadata Exception: pkg ebuild src:
          : sys-devel/gettext-0.19.4, attr data
ERROR root: error: bytes_ro_StringIO instance has no attribute '__len__'

media-sound/alsaplayer
  MissingChksum: version 0.99.81: "alsaplayer-0.99.81.tar.bz2" missing required chksums: sha512, whirlpool; has chksums: sha256, size

media-sound/ams
  MissingChksum: version 2.0.1: "ams-2.0.1.tar.bz2" missing required chksums: sha512, whirlpool; has chksums: sha256, size

media-sound/apetag
  DeprecatedEclass: version 1.12: uses deprecated eclass(es): [ python (migrate to python-r1 / python-single-r1 / python-any-r1) ]
  DeprecatedEAPI: version 1.12: uses deprecated EAPI: 3
  MissingChksum: version 1.12: "apetag.1.12.tar.gz" missing required chksums: sha512, whirlpool; has chksums: rmd160, sha1, sha256, size
ERROR pkgcore: caught unexpected exception accessing keywords from ebuild src:
             : sys-devel/gettext-0.19.4, exception Metadata Exception: pkg
             : ebuild src: sys-devel/gettext-0.19.4, attr keywords
ERROR pkgcore: error: Metadata Exception: pkg ebuild src:
             : sys-devel/gettext-0.19.4, attr data
ERROR pkgcore: error: bytes_ro_StringIO instance has no attribute '__len__'
ERROR pkgcore: None
ERROR root: check <pkgcheck.visibility.VisibilityReport object at
          : 0x7f138167b250> raised
ERROR root: Traceback (most recent call last):
ERROR root:   File "/usr/lib64/python2.7/site-packages/pkgcheck/base.py", line
          : 337, in feed
ERROR root:     check.feed(item, reporter)
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcheck/visibility.py", line
          : 264, in feed
ERROR root:     self.process_depset(pkg, attr, edepset, profiles, reporter)
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcheck/visibility.py", line
          : 315, in process_depset
ERROR root:     if any(True for pkg in src if visible(pkg)):
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcheck/visibility.py", line
          : 315, in <genexpr>
ERROR root:     if any(True for pkg in src if visible(pkg)):
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/restrictions/boolean.py
          : ", line 247, in match
ERROR root:     if not rest.match(vals):
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/package/base.py", line
          : 101, in dynamic_getattr_dict
ERROR root:     raise_from(MetadataException(self, attr, str(e)))
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/package/base.py", line
          : 93, in dynamic_getattr_dict
ERROR root:     val = functor(self)
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/ebuild/ebuild_src.py",
          : line 207, in <lambda>
ERROR root:     s.data.pop("KEYWORDS", "").split()))
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/package/base.py", line
          : 103, in dynamic_getattr_dict
ERROR root:     raise_from(MetadataException(self, attr, str(e)))
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/package/base.py", line
          : 93, in dynamic_getattr_dict
ERROR root:     val = functor(self)
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/package/metadata.py",
          : line 59, in _get_data
ERROR root:     return self._fetch_metadata()
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/ebuild/ebuild_src.py",
          : line 274, in _fetch_metadata
ERROR root:     return self._parent._get_metadata(self, ebp=ebp,
          : force_regen=force_regen)
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/ebuild/ebuild_src.py",
          : line 365, in _get_metadata
ERROR root:     return self._update_metadata(pkg, ebp=ebp)
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/ebuild/ebuild_src.py",
          : line 373, in _update_metadata
ERROR root:     mydata = my_proc.get_keys(pkg, self._ecache)
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/ebuild/processor.py",
          : line 835, in get_keys
ERROR root:     {"key": receive_key})
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/ebuild/processor.py",
          : line 768, in _run_depend_like_phase
ERROR root:     self.write("%s %i\n%s" % (command, len(data), data),
          : append_newline=False)
ERROR root: MetadataException: Metadata Exception: pkg ebuild src:
          : sys-devel/gettext-0.19.4, attr keywords
ERROR root: error: Metadata Exception: pkg ebuild src:
          : sys-devel/gettext-0.19.4, attr data
ERROR root: error: bytes_ro_StringIO instance has no attribute '__len__'
ERROR pkgcore: caught unexpected exception accessing keywords from ebuild src:
             : sys-devel/gettext-0.19.4, exception Metadata Exception: pkg
             : ebuild src: sys-devel/gettext-0.19.4, attr keywords
ERROR pkgcore: error: Metadata Exception: pkg ebuild src:
             : sys-devel/gettext-0.19.4, attr data
ERROR pkgcore: error: bytes_ro_StringIO instance has no attribute '__len__'
ERROR pkgcore: None
ERROR root: check <pkgcheck.visibility.VisibilityReport object at
          : 0x7f138167b250> raised
ERROR root: Traceback (most recent call last):
ERROR root:   File "/usr/lib64/python2.7/site-packages/pkgcheck/base.py", line
          : 337, in feed
ERROR root:     check.feed(item, reporter)
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcheck/visibility.py", line
          : 264, in feed
ERROR root:     self.process_depset(pkg, attr, edepset, profiles, reporter)
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcheck/visibility.py", line
          : 315, in process_depset
ERROR root:     if any(True for pkg in src if visible(pkg)):
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcheck/visibility.py", line
          : 315, in <genexpr>
ERROR root:     if any(True for pkg in src if visible(pkg)):
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/restrictions/boolean.py
          : ", line 247, in match
ERROR root:     if not rest.match(vals):
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/package/base.py", line
          : 101, in dynamic_getattr_dict
ERROR root:     raise_from(MetadataException(self, attr, str(e)))
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/package/base.py", line
          : 93, in dynamic_getattr_dict
ERROR root:     val = functor(self)
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/ebuild/ebuild_src.py",
          : line 207, in <lambda>
ERROR root:     s.data.pop("KEYWORDS", "").split()))
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/package/base.py", line
          : 103, in dynamic_getattr_dict
ERROR root:     raise_from(MetadataException(self, attr, str(e)))
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/package/base.py", line
          : 93, in dynamic_getattr_dict
ERROR root:     val = functor(self)
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/package/metadata.py",
          : line 59, in _get_data
ERROR root:     return self._fetch_metadata()
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/ebuild/ebuild_src.py",
          : line 274, in _fetch_metadata
ERROR root:     return self._parent._get_metadata(self, ebp=ebp,
          : force_regen=force_regen)
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/ebuild/ebuild_src.py",
          : line 365, in _get_metadata
ERROR root:     return self._update_metadata(pkg, ebp=ebp)
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/ebuild/ebuild_src.py",
          : line 373, in _update_metadata
ERROR root:     mydata = my_proc.get_keys(pkg, self._ecache)
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/ebuild/processor.py",
          : line 835, in get_keys
ERROR root:     {"key": receive_key})
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/ebuild/processor.py",
          : line 768, in _run_depend_like_phase
ERROR root:     self.write("%s %i\n%s" % (command, len(data), data),
          : append_newline=False)
ERROR root: MetadataException: Metadata Exception: pkg ebuild src:
          : sys-devel/gettext-0.19.4, attr keywords
ERROR root: error: Metadata Exception: pkg ebuild src:
          : sys-devel/gettext-0.19.4, attr data
ERROR root: error: bytes_ro_StringIO instance has no attribute '__len__'
ERROR pkgcore: caught unexpected exception accessing keywords from ebuild src:
             : sys-devel/gettext-0.19.4, exception Metadata Exception: pkg
             : ebuild src: sys-devel/gettext-0.19.4, attr keywords
ERROR pkgcore: error: Metadata Exception: pkg ebuild src:
             : sys-devel/gettext-0.19.4, attr data
ERROR pkgcore: error: bytes_ro_StringIO instance has no attribute '__len__'
ERROR pkgcore: None
ERROR root: check <pkgcheck.visibility.VisibilityReport object at
          : 0x7f138167b250> raised
ERROR root: Traceback (most recent call last):
ERROR root:   File "/usr/lib64/python2.7/site-packages/pkgcheck/base.py", line
          : 337, in feed
ERROR root:     check.feed(item, reporter)
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcheck/visibility.py", line
          : 264, in feed
ERROR root:     self.process_depset(pkg, attr, edepset, profiles, reporter)
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcheck/visibility.py", line
          : 315, in process_depset
ERROR root:     if any(True for pkg in src if visible(pkg)):
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcheck/visibility.py", line
          : 315, in <genexpr>
ERROR root:     if any(True for pkg in src if visible(pkg)):
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/restrictions/boolean.py
          : ", line 247, in match
ERROR root:     if not rest.match(vals):
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/package/base.py", line
          : 101, in dynamic_getattr_dict
ERROR root:     raise_from(MetadataException(self, attr, str(e)))
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/package/base.py", line
          : 93, in dynamic_getattr_dict
ERROR root:     val = functor(self)
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/ebuild/ebuild_src.py",
          : line 207, in <lambda>
ERROR root:     s.data.pop("KEYWORDS", "").split()))
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/package/base.py", line
          : 103, in dynamic_getattr_dict
ERROR root:     raise_from(MetadataException(self, attr, str(e)))
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/package/base.py", line
          : 93, in dynamic_getattr_dict
ERROR root:     val = functor(self)
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/package/metadata.py",
          : line 59, in _get_data
ERROR root:     return self._fetch_metadata()
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/ebuild/ebuild_src.py",
          : line 274, in _fetch_metadata
ERROR root:     return self._parent._get_metadata(self, ebp=ebp,
          : force_regen=force_regen)
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/ebuild/ebuild_src.py",
          : line 365, in _get_metadata
ERROR root:     return self._update_metadata(pkg, ebp=ebp)
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/ebuild/ebuild_src.py",
          : line 373, in _update_metadata
ERROR root:     mydata = my_proc.get_keys(pkg, self._ecache)
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/ebuild/processor.py",
          : line 835, in get_keys
ERROR root:     {"key": receive_key})
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/ebuild/processor.py",
          : line 768, in _run_depend_like_phase
ERROR root:     self.write("%s %i\n%s" % (command, len(data), data),
          : append_newline=False)
ERROR root: MetadataException: Metadata Exception: pkg ebuild src:
          : sys-devel/gettext-0.19.4, attr keywords
ERROR root: error: Metadata Exception: pkg ebuild src:
          : sys-devel/gettext-0.19.4, attr data
ERROR root: error: bytes_ro_StringIO instance has no attribute '__len__'
ERROR pkgcore: caught unexpected exception accessing keywords from ebuild src:
             : sys-devel/gettext-0.19.4, exception Metadata Exception: pkg
             : ebuild src: sys-devel/gettext-0.19.4, attr keywords
ERROR pkgcore: error: Metadata Exception: pkg ebuild src:
             : sys-devel/gettext-0.19.4, attr data
ERROR pkgcore: error: bytes_ro_StringIO instance has no attribute '__len__'
ERROR pkgcore: None
ERROR root: check <pkgcheck.visibility.VisibilityReport object at
          : 0x7f138167b250> raised
ERROR root: Traceback (most recent call last):
ERROR root:   File "/usr/lib64/python2.7/site-packages/pkgcheck/base.py", line
          : 337, in feed
ERROR root:     check.feed(item, reporter)
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcheck/visibility.py", line
          : 264, in feed
ERROR root:     self.process_depset(pkg, attr, edepset, profiles, reporter)
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcheck/visibility.py", line
          : 315, in process_depset
ERROR root:     if any(True for pkg in src if visible(pkg)):
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcheck/visibility.py", line
          : 315, in <genexpr>
ERROR root:     if any(True for pkg in src if visible(pkg)):
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/restrictions/boolean.py
          : ", line 247, in match
ERROR root:     if not rest.match(vals):
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/package/base.py", line
          : 101, in dynamic_getattr_dict
ERROR root:     raise_from(MetadataException(self, attr, str(e)))
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/package/base.py", line
          : 93, in dynamic_getattr_dict
ERROR root:     val = functor(self)
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/ebuild/ebuild_src.py",
          : line 207, in <lambda>
ERROR root:     s.data.pop("KEYWORDS", "").split()))
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/package/base.py", line
          : 103, in dynamic_getattr_dict
ERROR root:     raise_from(MetadataException(self, attr, str(e)))
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/package/base.py", line
          : 93, in dynamic_getattr_dict
ERROR root:     val = functor(self)
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/package/metadata.py",
          : line 59, in _get_data
ERROR root:     return self._fetch_metadata()
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/ebuild/ebuild_src.py",
          : line 274, in _fetch_metadata
ERROR root:     return self._parent._get_metadata(self, ebp=ebp,
          : force_regen=force_regen)
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/ebuild/ebuild_src.py",
          : line 365, in _get_metadata
ERROR root:     return self._update_metadata(pkg, ebp=ebp)
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/ebuild/ebuild_src.py",
          : line 373, in _update_metadata
ERROR root:     mydata = my_proc.get_keys(pkg, self._ecache)
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/ebuild/processor.py",
          : line 835, in get_keys
ERROR root:     {"key": receive_key})
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/ebuild/processor.py",
          : line 768, in _run_depend_like_phase
ERROR root:     self.write("%s %i\n%s" % (command, len(data), data),
          : append_newline=False)
ERROR root: MetadataException: Metadata Exception: pkg ebuild src:
          : sys-devel/gettext-0.19.4, attr keywords
ERROR root: error: Metadata Exception: pkg ebuild src:
          : sys-devel/gettext-0.19.4, attr data
ERROR root: error: bytes_ro_StringIO instance has no attribute '__len__'
ERROR pkgcore: caught unexpected exception accessing keywords from ebuild src:
             : sys-devel/gettext-0.19.4, exception Metadata Exception: pkg
             : ebuild src: sys-devel/gettext-0.19.4, attr keywords
ERROR pkgcore: error: Metadata Exception: pkg ebuild src:
             : sys-devel/gettext-0.19.4, attr data
ERROR pkgcore: error: bytes_ro_StringIO instance has no attribute '__len__'
ERROR pkgcore: None
ERROR root: check <pkgcheck.visibility.VisibilityReport object at
          : 0x7f138167b250> raised
ERROR root: Traceback (most recent call last):
ERROR root:   File "/usr/lib64/python2.7/site-packages/pkgcheck/base.py", line
          : 337, in feed
ERROR root:     check.feed(item, reporter)
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcheck/visibility.py", line
          : 264, in feed
ERROR root:     self.process_depset(pkg, attr, edepset, profiles, reporter)
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcheck/visibility.py", line
          : 315, in process_depset
ERROR root:     if any(True for pkg in src if visible(pkg)):
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcheck/visibility.py", line
          : 315, in <genexpr>
ERROR root:     if any(True for pkg in src if visible(pkg)):
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/restrictions/boolean.py
          : ", line 247, in match
ERROR root:     if not rest.match(vals):
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/package/base.py", line
          : 101, in dynamic_getattr_dict
ERROR root:     raise_from(MetadataException(self, attr, str(e)))
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/package/base.py", line
          : 93, in dynamic_getattr_dict
ERROR root:     val = functor(self)
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/ebuild/ebuild_src.py",
          : line 207, in <lambda>
ERROR root:     s.data.pop("KEYWORDS", "").split()))
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/package/base.py", line
          : 103, in dynamic_getattr_dict
ERROR root:     raise_from(MetadataException(self, attr, str(e)))
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/package/base.py", line
          : 93, in dynamic_getattr_dict
ERROR root:     val = functor(self)
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/package/metadata.py",
          : line 59, in _get_data
ERROR root:     return self._fetch_metadata()
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/ebuild/ebuild_src.py",
          : line 274, in _fetch_metadata
ERROR root:     return self._parent._get_metadata(self, ebp=ebp,
          : force_regen=force_regen)
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/ebuild/ebuild_src.py",
          : line 365, in _get_metadata
ERROR root:     return self._update_metadata(pkg, ebp=ebp)
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/ebuild/ebuild_src.py",
          : line 373, in _update_metadata
ERROR root:     mydata = my_proc.get_keys(pkg, self._ecache)
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/ebuild/processor.py",
          : line 835, in get_keys
ERROR root:     {"key": receive_key})
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/ebuild/processor.py",
          : line 768, in _run_depend_like_phase
ERROR root:     self.write("%s %i\n%s" % (command, len(data), data),
          : append_newline=False)
ERROR root: MetadataException: Metadata Exception: pkg ebuild src:
          : sys-devel/gettext-0.19.4, attr keywords
ERROR root: error: Metadata Exception: pkg ebuild src:
          : sys-devel/gettext-0.19.4, attr data
ERROR root: error: bytes_ro_StringIO instance has no attribute '__len__'
ERROR pkgcore: caught unexpected exception accessing keywords from ebuild src:
             : sys-devel/gettext-0.19.4, exception Metadata Exception: pkg
             : ebuild src: sys-devel/gettext-0.19.4, attr keywords
ERROR pkgcore: error: Metadata Exception: pkg ebuild src:
             : sys-devel/gettext-0.19.4, attr data
ERROR pkgcore: error: bytes_ro_StringIO instance has no attribute '__len__'
ERROR pkgcore: None
ERROR root: check <pkgcheck.visibility.VisibilityReport object at
          : 0x7f138167b250> raised
ERROR root: Traceback (most recent call last):
ERROR root:   File "/usr/lib64/python2.7/site-packages/pkgcheck/base.py", line
          : 337, in feed
ERROR root:     check.feed(item, reporter)
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcheck/visibility.py", line
          : 264, in feed
ERROR root:     self.process_depset(pkg, attr, edepset, profiles, reporter)
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcheck/visibility.py", line
          : 315, in process_depset
ERROR root:     if any(True for pkg in src if visible(pkg)):
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcheck/visibility.py", line
          : 315, in <genexpr>
ERROR root:     if any(True for pkg in src if visible(pkg)):
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/restrictions/boolean.py
          : ", line 247, in match
ERROR root:     if not rest.match(vals):
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/package/base.py", line
          : 101, in dynamic_getattr_dict
ERROR root:     raise_from(MetadataException(self, attr, str(e)))
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/package/base.py", line
          : 93, in dynamic_getattr_dict
ERROR root:     val = functor(self)
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/ebuild/ebuild_src.py",
          : line 207, in <lambda>
ERROR root:     s.data.pop("KEYWORDS", "").split()))
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/package/base.py", line
          : 103, in dynamic_getattr_dict
ERROR root:     raise_from(MetadataException(self, attr, str(e)))
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/package/base.py", line
          : 93, in dynamic_getattr_dict
ERROR root:     val = functor(self)
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/package/metadata.py",
          : line 59, in _get_data
ERROR root:     return self._fetch_metadata()
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/ebuild/ebuild_src.py",
          : line 274, in _fetch_metadata
ERROR root:     return self._parent._get_metadata(self, ebp=ebp,
          : force_regen=force_regen)
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/ebuild/ebuild_src.py",
          : line 365, in _get_metadata
ERROR root:     return self._update_metadata(pkg, ebp=ebp)
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/ebuild/ebuild_src.py",
          : line 373, in _update_metadata
ERROR root:     mydata = my_proc.get_keys(pkg, self._ecache)
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/ebuild/processor.py",
          : line 835, in get_keys
ERROR root:     {"key": receive_key})
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/ebuild/processor.py",
          : line 768, in _run_depend_like_phase
ERROR root:     self.write("%s %i\n%s" % (command, len(data), data),
          : append_newline=False)
ERROR root: MetadataException: Metadata Exception: pkg ebuild src:
          : sys-devel/gettext-0.19.4, attr keywords
ERROR root: error: Metadata Exception: pkg ebuild src:
          : sys-devel/gettext-0.19.4, attr data
ERROR root: error: bytes_ro_StringIO instance has no attribute '__len__'
ERROR pkgcore: caught unexpected exception accessing keywords from ebuild src:
             : sys-devel/gettext-0.19.4, exception Metadata Exception: pkg
             : ebuild src: sys-devel/gettext-0.19.4, attr keywords
ERROR pkgcore: error: Metadata Exception: pkg ebuild src:
             : sys-devel/gettext-0.19.4, attr data
ERROR pkgcore: error: bytes_ro_StringIO instance has no attribute '__len__'
ERROR pkgcore: None
ERROR root: check <pkgcheck.visibility.VisibilityReport object at
          : 0x7f138167b250> raised
ERROR root: Traceback (most recent call last):
ERROR root:   File "/usr/lib64/python2.7/site-packages/pkgcheck/base.py", line
          : 337, in feed
ERROR root:     check.feed(item, reporter)
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcheck/visibility.py", line
          : 264, in feed
ERROR root:     self.process_depset(pkg, attr, edepset, profiles, reporter)
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcheck/visibility.py", line
          : 315, in process_depset
ERROR root:     if any(True for pkg in src if visible(pkg)):
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcheck/visibility.py", line
          : 315, in <genexpr>
ERROR root:     if any(True for pkg in src if visible(pkg)):
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/restrictions/boolean.py
          : ", line 247, in match
ERROR root:     if not rest.match(vals):
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/package/base.py", line
          : 101, in dynamic_getattr_dict
ERROR root:     raise_from(MetadataException(self, attr, str(e)))
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/package/base.py", line
          : 93, in dynamic_getattr_dict
ERROR root:     val = functor(self)
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/ebuild/ebuild_src.py",
          : line 207, in <lambda>
ERROR root:     s.data.pop("KEYWORDS", "").split()))
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/package/base.py", line
          : 103, in dynamic_getattr_dict
ERROR root:     raise_from(MetadataException(self, attr, str(e)))
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/package/base.py", line
          : 93, in dynamic_getattr_dict
ERROR root:     val = functor(self)
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/package/metadata.py",
          : line 59, in _get_data
ERROR root:     return self._fetch_metadata()
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/ebuild/ebuild_src.py",
          : line 274, in _fetch_metadata
ERROR root:     return self._parent._get_metadata(self, ebp=ebp,
          : force_regen=force_regen)
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/ebuild/ebuild_src.py",
          : line 365, in _get_metadata
ERROR root:     return self._update_metadata(pkg, ebp=ebp)
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/ebuild/ebuild_src.py",
          : line 373, in _update_metadata
ERROR root:     mydata = my_proc.get_keys(pkg, self._ecache)
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/ebuild/processor.py",
          : line 835, in get_keys
ERROR root:     {"key": receive_key})
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/ebuild/processor.py",
          : line 768, in _run_depend_like_phase
ERROR root:     self.write("%s %i\n%s" % (command, len(data), data),
          : append_newline=False)
ERROR root: MetadataException: Metadata Exception: pkg ebuild src:
          : sys-devel/gettext-0.19.4, attr keywords
ERROR root: error: Metadata Exception: pkg ebuild src:
          : sys-devel/gettext-0.19.4, attr data
ERROR root: error: bytes_ro_StringIO instance has no attribute '__len__'
ERROR pkgcore: caught unexpected exception accessing keywords from ebuild src:
             : sys-devel/gettext-0.19.4, exception Metadata Exception: pkg
             : ebuild src: sys-devel/gettext-0.19.4, attr keywords
ERROR pkgcore: error: Metadata Exception: pkg ebuild src:
             : sys-devel/gettext-0.19.4, attr data
ERROR pkgcore: error: bytes_ro_StringIO instance has no attribute '__len__'
ERROR pkgcore: None
ERROR root: check <pkgcheck.visibility.VisibilityReport object at
          : 0x7f138167b250> raised
ERROR root: Traceback (most recent call last):
ERROR root:   File "/usr/lib64/python2.7/site-packages/pkgcheck/base.py", line
          : 337, in feed
ERROR root:     check.feed(item, reporter)
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcheck/visibility.py", line
          : 264, in feed
ERROR root:     self.process_depset(pkg, attr, edepset, profiles, reporter)
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcheck/visibility.py", line
          : 315, in process_depset
ERROR root:     if any(True for pkg in src if visible(pkg)):
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcheck/visibility.py", line
          : 315, in <genexpr>
ERROR root:     if any(True for pkg in src if visible(pkg)):
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/restrictions/boolean.py
          : ", line 247, in match
ERROR root:     if not rest.match(vals):
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/package/base.py", line
          : 101, in dynamic_getattr_dict
ERROR root:     raise_from(MetadataException(self, attr, str(e)))
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/package/base.py", line
          : 93, in dynamic_getattr_dict
ERROR root:     val = functor(self)
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/ebuild/ebuild_src.py",
          : line 207, in <lambda>
ERROR root:     s.data.pop("KEYWORDS", "").split()))
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/package/base.py", line
          : 103, in dynamic_getattr_dict
ERROR root:     raise_from(MetadataException(self, attr, str(e)))
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/package/base.py", line
          : 93, in dynamic_getattr_dict
ERROR root:     val = functor(self)
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/package/metadata.py",
          : line 59, in _get_data
ERROR root:     return self._fetch_metadata()
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/ebuild/ebuild_src.py",
          : line 274, in _fetch_metadata
ERROR root:     return self._parent._get_metadata(self, ebp=ebp,
          : force_regen=force_regen)
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/ebuild/ebuild_src.py",
          : line 365, in _get_metadata
ERROR root:     return self._update_metadata(pkg, ebp=ebp)
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/ebuild/ebuild_src.py",
          : line 373, in _update_metadata
ERROR root:     mydata = my_proc.get_keys(pkg, self._ecache)
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/ebuild/processor.py",
          : line 835, in get_keys
ERROR root:     {"key": receive_key})
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/ebuild/processor.py",
          : line 768, in _run_depend_like_phase
ERROR root:     self.write("%s %i\n%s" % (command, len(data), data),
          : append_newline=False)
ERROR root: MetadataException: Metadata Exception: pkg ebuild src:
          : sys-devel/gettext-0.19.4, attr keywords
ERROR root: error: Metadata Exception: pkg ebuild src:
          : sys-devel/gettext-0.19.4, attr data
ERROR root: error: bytes_ro_StringIO instance has no attribute '__len__'
ERROR pkgcore: caught unexpected exception accessing keywords from ebuild src:
             : sys-devel/gettext-0.19.4, exception Metadata Exception: pkg
             : ebuild src: sys-devel/gettext-0.19.4, attr keywords
ERROR pkgcore: error: Metadata Exception: pkg ebuild src:
             : sys-devel/gettext-0.19.4, attr data
ERROR pkgcore: error: bytes_ro_StringIO instance has no attribute '__len__'
ERROR pkgcore: None
ERROR root: check <pkgcheck.visibility.VisibilityReport object at
          : 0x7f138167b250> raised
ERROR root: Traceback (most recent call last):
ERROR root:   File "/usr/lib64/python2.7/site-packages/pkgcheck/base.py", line
          : 337, in feed
ERROR root:     check.feed(item, reporter)
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcheck/visibility.py", line
          : 264, in feed
ERROR root:     self.process_depset(pkg, attr, edepset, profiles, reporter)
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcheck/visibility.py", line
          : 315, in process_depset
ERROR root:     if any(True for pkg in src if visible(pkg)):
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcheck/visibility.py", line
          : 315, in <genexpr>
ERROR root:     if any(True for pkg in src if visible(pkg)):
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/restrictions/boolean.py
          : ", line 247, in match
ERROR root:     if not rest.match(vals):
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/package/base.py", line
          : 101, in dynamic_getattr_dict
ERROR root:     raise_from(MetadataException(self, attr, str(e)))
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/package/base.py", line
          : 93, in dynamic_getattr_dict
ERROR root:     val = functor(self)
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/ebuild/ebuild_src.py",
          : line 207, in <lambda>
ERROR root:     s.data.pop("KEYWORDS", "").split()))
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/package/base.py", line
          : 103, in dynamic_getattr_dict
ERROR root:     raise_from(MetadataException(self, attr, str(e)))
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/package/base.py", line
          : 93, in dynamic_getattr_dict
ERROR root:     val = functor(self)
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/package/metadata.py",
          : line 59, in _get_data
ERROR root:     return self._fetch_metadata()
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/ebuild/ebuild_src.py",
          : line 274, in _fetch_metadata
ERROR root:     return self._parent._get_metadata(self, ebp=ebp,
          : force_regen=force_regen)
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/ebuild/ebuild_src.py",
          : line 365, in _get_metadata
ERROR root:     return self._update_metadata(pkg, ebp=ebp)
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/ebuild/ebuild_src.py",
          : line 373, in _update_metadata
ERROR root:     mydata = my_proc.get_keys(pkg, self._ecache)
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/ebuild/processor.py",
          : line 835, in get_keys
ERROR root:     {"key": receive_key})
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/ebuild/processor.py",
          : line 768, in _run_depend_like_phase
ERROR root:     self.write("%s %i\n%s" % (command, len(data), data),
          : append_newline=False)
ERROR root: MetadataException: Metadata Exception: pkg ebuild src:
          : sys-devel/gettext-0.19.4, attr keywords
ERROR root: error: Metadata Exception: pkg ebuild src:
          : sys-devel/gettext-0.19.4, attr data
ERROR root: error: bytes_ro_StringIO instance has no attribute '__len__'

media-sound/ardour
  DeprecatedEclass: version 9999: uses deprecated eclass(es): [ git-2 (migrate to git-r3) ]

media-sound/ario
  DeprecatedEclass: version 1.5.1: uses deprecated eclass(es): [ python (migrate to python-r1 / python-single-r1 / python-any-r1) ]
ERROR pkgcore: caught unexpected exception accessing keywords from ebuild src:
             : sys-devel/gettext-0.19.4, exception Metadata Exception: pkg
             : ebuild src: sys-devel/gettext-0.19.4, attr keywords
ERROR pkgcore: error: Metadata Exception: pkg ebuild src:
             : sys-devel/gettext-0.19.4, attr data
ERROR pkgcore: error: bytes_ro_StringIO instance has no attribute '__len__'
ERROR pkgcore: None
ERROR root: check <pkgcheck.visibility.VisibilityReport object at
          : 0x7f138167b250> raised
ERROR root: Traceback (most recent call last):
ERROR root:   File "/usr/lib64/python2.7/site-packages/pkgcheck/base.py", line
          : 337, in feed
ERROR root:     check.feed(item, reporter)
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcheck/visibility.py", line
          : 264, in feed
ERROR root:     self.process_depset(pkg, attr, edepset, profiles, reporter)
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcheck/visibility.py", line
          : 315, in process_depset
ERROR root:     if any(True for pkg in src if visible(pkg)):
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcheck/visibility.py", line
          : 315, in <genexpr>
ERROR root:     if any(True for pkg in src if visible(pkg)):
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/restrictions/boolean.py
          : ", line 247, in match
ERROR root:     if not rest.match(vals):
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/package/base.py", line
          : 101, in dynamic_getattr_dict
ERROR root:     raise_from(MetadataException(self, attr, str(e)))
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/package/base.py", line
          : 93, in dynamic_getattr_dict
ERROR root:     val = functor(self)
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/ebuild/ebuild_src.py",
          : line 207, in <lambda>
ERROR root:     s.data.pop("KEYWORDS", "").split()))
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/package/base.py", line
          : 103, in dynamic_getattr_dict
ERROR root:     raise_from(MetadataException(self, attr, str(e)))
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/package/base.py", line
          : 93, in dynamic_getattr_dict
ERROR root:     val = functor(self)
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/package/metadata.py",
          : line 59, in _get_data
ERROR root:     return self._fetch_metadata()
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/ebuild/ebuild_src.py",
          : line 274, in _fetch_metadata
ERROR root:     return self._parent._get_metadata(self, ebp=ebp,
          : force_regen=force_regen)
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/ebuild/ebuild_src.py",
          : line 365, in _get_metadata
ERROR root:     return self._update_metadata(pkg, ebp=ebp)
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/ebuild/ebuild_src.py",
          : line 373, in _update_metadata
ERROR root:     mydata = my_proc.get_keys(pkg, self._ecache)
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/ebuild/processor.py",
          : line 835, in get_keys
ERROR root:     {"key": receive_key})
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/ebuild/processor.py",
          : line 768, in _run_depend_like_phase
ERROR root:     self.write("%s %i\n%s" % (command, len(data), data),
          : append_newline=False)
ERROR root: MetadataException: Metadata Exception: pkg ebuild src:
          : sys-devel/gettext-0.19.4, attr keywords
ERROR root: error: Metadata Exception: pkg ebuild src:
          : sys-devel/gettext-0.19.4, attr data
ERROR root: error: bytes_ro_StringIO instance has no attribute '__len__'

media-sound/aseqview
  DeprecatedEAPI: version 0.2.8: uses deprecated EAPI: 2
  MissingChksum: version 0.2.8: "aseqview-0.2.8.tar.gz" missing required chksums: sha512, whirlpool; has chksums: sha256, size
ERROR pkgcore: caught unexpected exception accessing keywords from ebuild src:
             : sys-devel/gettext-0.19.4, exception Metadata Exception: pkg
             : ebuild src: sys-devel/gettext-0.19.4, attr keywords
ERROR pkgcore: error: Metadata Exception: pkg ebuild src:
             : sys-devel/gettext-0.19.4, attr data
ERROR pkgcore: error: bytes_ro_StringIO instance has no attribute '__len__'
ERROR pkgcore: None
ERROR root: check <pkgcheck.visibility.VisibilityReport object at
          : 0x7f138167b250> raised
ERROR root: Traceback (most recent call last):
ERROR root:   File "/usr/lib64/python2.7/site-packages/pkgcheck/base.py", line
          : 337, in feed
ERROR root:     check.feed(item, reporter)
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcheck/visibility.py", line
          : 264, in feed
ERROR root:     self.process_depset(pkg, attr, edepset, profiles, reporter)
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcheck/visibility.py", line
          : 315, in process_depset
ERROR root:     if any(True for pkg in src if visible(pkg)):
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcheck/visibility.py", line
          : 315, in <genexpr>
ERROR root:     if any(True for pkg in src if visible(pkg)):
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/restrictions/boolean.py
          : ", line 247, in match
ERROR root:     if not rest.match(vals):
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/package/base.py", line
          : 101, in dynamic_getattr_dict
ERROR root:     raise_from(MetadataException(self, attr, str(e)))
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/package/base.py", line
          : 93, in dynamic_getattr_dict
ERROR root:     val = functor(self)
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/ebuild/ebuild_src.py",
          : line 207, in <lambda>
ERROR root:     s.data.pop("KEYWORDS", "").split()))
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/package/base.py", line
          : 103, in dynamic_getattr_dict
ERROR root:     raise_from(MetadataException(self, attr, str(e)))
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/package/base.py", line
          : 93, in dynamic_getattr_dict
ERROR root:     val = functor(self)
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/package/metadata.py",
          : line 59, in _get_data
ERROR root:     return self._fetch_metadata()
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/ebuild/ebuild_src.py",
          : line 274, in _fetch_metadata
ERROR root:     return self._parent._get_metadata(self, ebp=ebp,
          : force_regen=force_regen)
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/ebuild/ebuild_src.py",
          : line 365, in _get_metadata
ERROR root:     return self._update_metadata(pkg, ebp=ebp)
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/ebuild/ebuild_src.py",
          : line 373, in _update_metadata
ERROR root:     mydata = my_proc.get_keys(pkg, self._ecache)
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/ebuild/processor.py",
          : line 835, in get_keys
ERROR root:     {"key": receive_key})
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/ebuild/processor.py",
          : line 768, in _run_depend_like_phase
ERROR root:     self.write("%s %i\n%s" % (command, len(data), data),
          : append_newline=False)
ERROR root: MetadataException: Metadata Exception: pkg ebuild src:
          : sys-devel/gettext-0.19.4, attr keywords
ERROR root: error: Metadata Exception: pkg ebuild src:
          : sys-devel/gettext-0.19.4, attr data
ERROR root: error: bytes_ro_StringIO instance has no attribute '__len__'
ERROR pkgcore: caught unexpected exception accessing keywords from ebuild src:
             : sys-devel/gettext-0.19.4, exception Metadata Exception: pkg
             : ebuild src: sys-devel/gettext-0.19.4, attr keywords
ERROR pkgcore: error: Metadata Exception: pkg ebuild src:
             : sys-devel/gettext-0.19.4, attr data
ERROR pkgcore: error: bytes_ro_StringIO instance has no attribute '__len__'
ERROR pkgcore: None
ERROR root: check <pkgcheck.visibility.VisibilityReport object at
          : 0x7f138167b250> raised
ERROR root: Traceback (most recent call last):
ERROR root:   File "/usr/lib64/python2.7/site-packages/pkgcheck/base.py", line
          : 337, in feed
ERROR root:     check.feed(item, reporter)
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcheck/visibility.py", line
          : 264, in feed
ERROR root:     self.process_depset(pkg, attr, edepset, profiles, reporter)
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcheck/visibility.py", line
          : 315, in process_depset
ERROR root:     if any(True for pkg in src if visible(pkg)):
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcheck/visibility.py", line
          : 315, in <genexpr>
ERROR root:     if any(True for pkg in src if visible(pkg)):
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/restrictions/boolean.py
          : ", line 247, in match
ERROR root:     if not rest.match(vals):
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/package/base.py", line
          : 101, in dynamic_getattr_dict
ERROR root:     raise_from(MetadataException(self, attr, str(e)))
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/package/base.py", line
          : 93, in dynamic_getattr_dict
ERROR root:     val = functor(self)
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/ebuild/ebuild_src.py",
          : line 207, in <lambda>
ERROR root:     s.data.pop("KEYWORDS", "").split()))
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/package/base.py", line
          : 103, in dynamic_getattr_dict
ERROR root:     raise_from(MetadataException(self, attr, str(e)))
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/package/base.py", line
          : 93, in dynamic_getattr_dict
ERROR root:     val = functor(self)
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/package/metadata.py",
          : line 59, in _get_data
ERROR root:     return self._fetch_metadata()
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/ebuild/ebuild_src.py",
          : line 274, in _fetch_metadata
ERROR root:     return self._parent._get_metadata(self, ebp=ebp,
          : force_regen=force_regen)
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/ebuild/ebuild_src.py",
          : line 365, in _get_metadata
ERROR root:     return self._update_metadata(pkg, ebp=ebp)
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/ebuild/ebuild_src.py",
          : line 373, in _update_metadata
ERROR root:     mydata = my_proc.get_keys(pkg, self._ecache)
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/ebuild/processor.py",
          : line 835, in get_keys
ERROR root:     {"key": receive_key})
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/ebuild/processor.py",
          : line 768, in _run_depend_like_phase
ERROR root:     self.write("%s %i\n%s" % (command, len(data), data),
          : append_newline=False)
ERROR root: MetadataException: Metadata Exception: pkg ebuild src:
          : sys-devel/gettext-0.19.4, attr keywords
ERROR root: error: Metadata Exception: pkg ebuild src:
          : sys-devel/gettext-0.19.4, attr data
ERROR root: error: bytes_ro_StringIO instance has no attribute '__len__'
ERROR pkgcore: caught unexpected exception accessing keywords from ebuild src:
             : sys-devel/gettext-0.19.4, exception Metadata Exception: pkg
             : ebuild src: sys-devel/gettext-0.19.4, attr keywords
ERROR pkgcore: error: Metadata Exception: pkg ebuild src:
             : sys-devel/gettext-0.19.4, attr data
ERROR pkgcore: error: bytes_ro_StringIO instance has no attribute '__len__'
ERROR pkgcore: None
ERROR root: check <pkgcheck.visibility.VisibilityReport object at
          : 0x7f138167b250> raised
ERROR root: Traceback (most recent call last):
ERROR root:   File "/usr/lib64/python2.7/site-packages/pkgcheck/base.py", line
          : 337, in feed
ERROR root:     check.feed(item, reporter)
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcheck/visibility.py", line
          : 264, in feed
ERROR root:     self.process_depset(pkg, attr, edepset, profiles, reporter)
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcheck/visibility.py", line
          : 315, in process_depset
ERROR root:     if any(True for pkg in src if visible(pkg)):
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcheck/visibility.py", line
          : 315, in <genexpr>
ERROR root:     if any(True for pkg in src if visible(pkg)):
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/restrictions/boolean.py
          : ", line 247, in match
ERROR root:     if not rest.match(vals):
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/package/base.py", line
          : 101, in dynamic_getattr_dict
ERROR root:     raise_from(MetadataException(self, attr, str(e)))
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/package/base.py", line
          : 93, in dynamic_getattr_dict
ERROR root:     val = functor(self)
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/ebuild/ebuild_src.py",
          : line 207, in <lambda>
ERROR root:     s.data.pop("KEYWORDS", "").split()))
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/package/base.py", line
          : 103, in dynamic_getattr_dict
ERROR root:     raise_from(MetadataException(self, attr, str(e)))
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/package/base.py", line
          : 93, in dynamic_getattr_dict
ERROR root:     val = functor(self)
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/package/metadata.py",
          : line 59, in _get_data
ERROR root:     return self._fetch_metadata()
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/ebuild/ebuild_src.py",
          : line 274, in _fetch_metadata
ERROR root:     return self._parent._get_metadata(self, ebp=ebp,
          : force_regen=force_regen)
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/ebuild/ebuild_src.py",
          : line 365, in _get_metadata
ERROR root:     return self._update_metadata(pkg, ebp=ebp)
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/ebuild/ebuild_src.py",
          : line 373, in _update_metadata
ERROR root:     mydata = my_proc.get_keys(pkg, self._ecache)
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/ebuild/processor.py",
          : line 835, in get_keys
ERROR root:     {"key": receive_key})
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/ebuild/processor.py",
          : line 768, in _run_depend_like_phase
ERROR root:     self.write("%s %i\n%s" % (command, len(data), data),
          : append_newline=False)
ERROR root: MetadataException: Metadata Exception: pkg ebuild src:
          : sys-devel/gettext-0.19.4, attr keywords
ERROR root: error: Metadata Exception: pkg ebuild src:
          : sys-devel/gettext-0.19.4, attr data
ERROR root: error: bytes_ro_StringIO instance has no attribute '__len__'

media-sound/asunder
  DroppedKeywordWarning: version 2.5: keywords dropped: ppc

media-sound/audacious
  DeprecatedEAPI: version 2.4.4: uses deprecated EAPI: 1

media-sound/audiocompress
  DeprecatedEAPI: version 2.0: uses deprecated EAPI: 0
  MissingChksum: version 2.0: "AudioCompress-2.0.tar.gz" missing required chksums: sha512, whirlpool; has chksums: rmd160, sha1, sha256, size

media-sound/audiotag
  DeprecatedEAPI: version 0.19: uses deprecated EAPI: 0
  MissingChksum: version 0.19: "audiotag-0.19.tar.bz2" missing required chksums: sha512, whirlpool; has chksums: sha256, size

media-sound/aumix
  DeprecatedEAPI: version 2.9.1: uses deprecated EAPI: 2
ERROR pkgcore: caught unexpected exception accessing keywords from ebuild src:
             : sys-devel/gettext-0.19.4, exception Metadata Exception: pkg
             : ebuild src: sys-devel/gettext-0.19.4, attr keywords
ERROR pkgcore: error: Metadata Exception: pkg ebuild src:
             : sys-devel/gettext-0.19.4, attr data
ERROR pkgcore: error: bytes_ro_StringIO instance has no attribute '__len__'
ERROR pkgcore: None
ERROR root: check <pkgcheck.visibility.VisibilityReport object at
          : 0x7f138167b250> raised
ERROR root: Traceback (most recent call last):
ERROR root:   File "/usr/lib64/python2.7/site-packages/pkgcheck/base.py", line
          : 337, in feed
ERROR root:     check.feed(item, reporter)
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcheck/visibility.py", line
          : 264, in feed
ERROR root:     self.process_depset(pkg, attr, edepset, profiles, reporter)
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcheck/visibility.py", line
          : 315, in process_depset
ERROR root:     if any(True for pkg in src if visible(pkg)):
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcheck/visibility.py", line
          : 315, in <genexpr>
ERROR root:     if any(True for pkg in src if visible(pkg)):
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/restrictions/boolean.py
          : ", line 247, in match
ERROR root:     if not rest.match(vals):
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/package/base.py", line
          : 101, in dynamic_getattr_dict
ERROR root:     raise_from(MetadataException(self, attr, str(e)))
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/package/base.py", line
          : 93, in dynamic_getattr_dict
ERROR root:     val = functor(self)
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/ebuild/ebuild_src.py",
          : line 207, in <lambda>
ERROR root:     s.data.pop("KEYWORDS", "").split()))
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/package/base.py", line
          : 103, in dynamic_getattr_dict
ERROR root:     raise_from(MetadataException(self, attr, str(e)))
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/package/base.py", line
          : 93, in dynamic_getattr_dict
ERROR root:     val = functor(self)
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/package/metadata.py",
          : line 59, in _get_data
ERROR root:     return self._fetch_metadata()
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/ebuild/ebuild_src.py",
          : line 274, in _fetch_metadata
ERROR root:     return self._parent._get_metadata(self, ebp=ebp,
          : force_regen=force_regen)
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/ebuild/ebuild_src.py",
          : line 365, in _get_metadata
ERROR root:     return self._update_metadata(pkg, ebp=ebp)
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/ebuild/ebuild_src.py",
          : line 373, in _update_metadata
ERROR root:     mydata = my_proc.get_keys(pkg, self._ecache)
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/ebuild/processor.py",
          : line 835, in get_keys
ERROR root:     {"key": receive_key})
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/ebuild/processor.py",
          : line 768, in _run_depend_like_phase
ERROR root:     self.write("%s %i\n%s" % (command, len(data), data),
          : append_newline=False)
ERROR root: MetadataException: Metadata Exception: pkg ebuild src:
          : sys-devel/gettext-0.19.4, attr keywords
ERROR root: error: Metadata Exception: pkg ebuild src:
          : sys-devel/gettext-0.19.4, attr data
ERROR root: error: bytes_ro_StringIO instance has no attribute '__len__'
  MissingChksum: version 2.9.1: "aumix-2.9.1.tar.bz2" missing required chksums: sha512, whirlpool; has chksums: rmd160, sha1, sha256, size

media-sound/awesfx
  MissingChksum: version 0.5.1d: "awesfx-0.5.1d.tar.bz2" missing required chksums: sha512, whirlpool; has chksums: sha256, size

media-sound/banshee
  DeprecatedEclass: version 2.6.1: uses deprecated eclass(es): [ mono (migrate to mono-env) ]

media-sound/baudline
  DeprecatedEAPI: version 1.08-r1: uses deprecated EAPI: 3
  MissingChksum: version 1.08-r1: "baudline_1.08_linux_ppc.tar.gz" missing required chksums: sha512, whirlpool; has chksums: sha256, size
  MissingChksum: version 1.08-r1: "baudline_1.08_linux_s390.tar.gz" missing required chksums: sha512, whirlpool; has chksums: sha256, size
  MissingChksum: version 1.08-r1: "baudline_1.08_linux_i686.tar.gz" missing required chksums: sha512, whirlpool; has chksums: sha256, size

media-sound/bitmeter
  DeprecatedEAPI: version 1.2: uses deprecated EAPI: 2
  MissingChksum: version 1.2: "bitmeter-1.2.tar.gz" missing required chksums: sha512, whirlpool; has chksums: rmd160, sha1, sha256, size

media-sound/bladeenc
  DeprecatedEAPI: version 0.94.2-r1: uses deprecated EAPI: 2
  MissingChksum: version 0.94.2-r1: "bladeenc-0.94.2-src-stable.tar.gz" missing required chksums: sha512, whirlpool; has chksums: rmd160, sha1, sha256, size

media-sound/bplay
  DeprecatedEAPI: version 0.991: uses deprecated EAPI: 0
  MissingChksum: version 0.991: "bplay-0.991.tar.gz" missing required chksums: sha512, whirlpool; has chksums: sha256, size

media-sound/bpmdetect
  DeprecatedEAPI: version 0.6.1: uses deprecated EAPI: 2
  MissingChksum: version 0.6.1: "bpmdetect-0.6.1-src.tar.bz2" missing required chksums: sha512, whirlpool; has chksums: sha256, size

media-sound/brutefir
  DeprecatedEAPI: version 1.0k-r1: uses deprecated EAPI: 2
  MissingChksum: version 1.0k-r1: "brutefir-1.0k.tar.gz" missing required chksums: sha512, whirlpool; has chksums: sha256, size
ERROR pkgcore: caught unexpected exception accessing keywords from ebuild src:
             : sys-devel/gettext-0.19.4, exception Metadata Exception: pkg
             : ebuild src: sys-devel/gettext-0.19.4, attr keywords
ERROR pkgcore: error: Metadata Exception: pkg ebuild src:
             : sys-devel/gettext-0.19.4, attr data
ERROR pkgcore: error: bytes_ro_StringIO instance has no attribute '__len__'
ERROR pkgcore: None
ERROR root: check <pkgcheck.visibility.VisibilityReport object at
          : 0x7f138167b250> raised
ERROR root: Traceback (most recent call last):
ERROR root:   File "/usr/lib64/python2.7/site-packages/pkgcheck/base.py", line
          : 337, in feed
ERROR root:     check.feed(item, reporter)
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcheck/visibility.py", line
          : 264, in feed
ERROR root:     self.process_depset(pkg, attr, edepset, profiles, reporter)
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcheck/visibility.py", line
          : 315, in process_depset
ERROR root:     if any(True for pkg in src if visible(pkg)):
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcheck/visibility.py", line
          : 315, in <genexpr>
ERROR root:     if any(True for pkg in src if visible(pkg)):
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/restrictions/boolean.py
          : ", line 247, in match
ERROR root:     if not rest.match(vals):
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/package/base.py", line
          : 101, in dynamic_getattr_dict
ERROR root:     raise_from(MetadataException(self, attr, str(e)))
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/package/base.py", line
          : 93, in dynamic_getattr_dict
ERROR root:     val = functor(self)
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/ebuild/ebuild_src.py",
          : line 207, in <lambda>
ERROR root:     s.data.pop("KEYWORDS", "").split()))
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/package/base.py", line
          : 103, in dynamic_getattr_dict
ERROR root:     raise_from(MetadataException(self, attr, str(e)))
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/package/base.py", line
          : 93, in dynamic_getattr_dict
ERROR root:     val = functor(self)
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/package/metadata.py",
          : line 59, in _get_data
ERROR root:     return self._fetch_metadata()
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/ebuild/ebuild_src.py",
          : line 274, in _fetch_metadata
ERROR root:     return self._parent._get_metadata(self, ebp=ebp,
          : force_regen=force_regen)
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/ebuild/ebuild_src.py",
          : line 365, in _get_metadata
ERROR root:     return self._update_metadata(pkg, ebp=ebp)
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/ebuild/ebuild_src.py",
          : line 373, in _update_metadata
ERROR root:     mydata = my_proc.get_keys(pkg, self._ecache)
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/ebuild/processor.py",
          : line 835, in get_keys
ERROR root:     {"key": receive_key})
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/ebuild/processor.py",
          : line 768, in _run_depend_like_phase
ERROR root:     self.write("%s %i\n%s" % (command, len(data), data),
          : append_newline=False)
ERROR root: MetadataException: Metadata Exception: pkg ebuild src:
          : sys-devel/gettext-0.19.4, attr keywords
ERROR root: error: Metadata Exception: pkg ebuild src:
          : sys-devel/gettext-0.19.4, attr data
ERROR root: error: bytes_ro_StringIO instance has no attribute '__len__'

media-sound/cdplay
  DeprecatedEAPI: version 1.0: uses deprecated EAPI: 0
  MissingChksum: version 1.0: "cdplay-1.0.tar.gz" missing required chksums: sha512, whirlpool; has chksums: rmd160, sha1, sha256, size

media-sound/chordii
  MissingChksum: version 4.3: "chordii-4.3.tar.gz" missing required chksums: sha512, whirlpool; has chksums: sha256, size
  MissingChksum: version 4.3: "chordii-4.3-user_guide.pdf" missing required chksums: sha512, whirlpool; has chksums: sha256, size

media-sound/christine
  DeprecatedEclass: version 0.7.0: uses deprecated eclass(es): [ python (migrate to python-r1 / python-single-r1 / python-any-r1) ]
  MissingChksum: version 0.7.0: "christine-0.7.0.tar.bz2" missing required chksums: sha512, whirlpool; has chksums: sha256, size

media-sound/chuck
  DeprecatedEAPI: version 1.2.1.2: uses deprecated EAPI: 0
  DeprecatedEAPI: versi