+ JOB=12
+ NO_JOBS=16
+ [[ ! -n 12 ]]
+ [[ ! -n 16 ]]
+ [[ 12 == global ]]
+ set +x
+ pkgcheck -r gentoo --reporter FancyReporter 'app-text/*' 'dev-php/*' 'dev-vcs/*' 'kde-misc/*' 'www-apache/*' 'media-tv/*' 'sys-power/*' 'sys-freebsd/*' 'www-plugins/*' 'games-mud/*' -d imlate -d unstable_only -d cleanup -d stale_unstable -d UnusedGlobalFlags -d UnusedLicense --profile-disable-dev --profile-disable-exp
WARNING pkgcore: invalid glsa- glsa-201206-24.xml, package www-servers/tomcat:
               : error range rlt version 5.5.34 is a guaranteed empty set

app-text/7plus
  DeprecatedEAPI: version 2.25: uses deprecated EAPI: 0
ERROR pkgcore: caught unexpected exception accessing keywords from ebuild src:
             : sys-devel/gettext-0.19.4, exception Metadata Exception: pkg
             : ebuild src: sys-devel/gettext-0.19.4, attr keywords
ERROR pkgcore: error: Metadata Exception: pkg ebuild src:
             : sys-devel/gettext-0.19.4, attr data
ERROR pkgcore: error: bytes_ro_StringIO instance has no attribute '__len__'
ERROR pkgcore: None
ERROR root: check <pkgcheck.visibility.VisibilityReport object at
          : 0x7f4e389710d0> raised
ERROR root: Traceback (most recent call last):
ERROR root:   File "/usr/lib64/python2.7/site-packages/pkgcheck/base.py", line
          : 337, in feed
ERROR root:     check.feed(item, reporter)
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcheck/visibility.py", line
          : 264, in feed
ERROR root:     self.process_depset(pkg, attr, edepset, profiles, reporter)
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcheck/visibility.py", line
          : 315, in process_depset
ERROR root:     if any(True for pkg in src if visible(pkg)):
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcheck/visibility.py", line
          : 315, in <genexpr>
ERROR root:     if any(True for pkg in src if visible(pkg)):
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/restrictions/boolean.py
          : ", line 247, in match
ERROR root:     if not rest.match(vals):
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/package/base.py", line
          : 101, in dynamic_getattr_dict
ERROR root:     raise_from(MetadataException(self, attr, str(e)))
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/package/base.py", line
          : 93, in dynamic_getattr_dict
ERROR root:     val = functor(self)
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/ebuild/ebuild_src.py",
          : line 207, in <lambda>
ERROR root:     s.data.pop("KEYWORDS", "").split()))
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/package/base.py", line
          : 103, in dynamic_getattr_dict
ERROR root:     raise_from(MetadataException(self, attr, str(e)))
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/package/base.py", line
          : 93, in dynamic_getattr_dict
ERROR root:     val = functor(self)
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/package/metadata.py",
          : line 59, in _get_data
ERROR root:     return self._fetch_metadata()
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/ebuild/ebuild_src.py",
          : line 274, in _fetch_metadata
ERROR root:     return self._parent._get_metadata(self, ebp=ebp,
          : force_regen=force_regen)
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/ebuild/ebuild_src.py",
          : line 365, in _get_metadata
ERROR root:     return self._update_metadata(pkg, ebp=ebp)
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/ebuild/ebuild_src.py",
          : line 373, in _update_metadata
ERROR root:     mydata = my_proc.get_keys(pkg, self._ecache)
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/ebuild/processor.py",
          : line 835, in get_keys
ERROR root:     {"key": receive_key})
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/ebuild/processor.py",
          : line 768, in _run_depend_like_phase
ERROR root:     self.write("%s %i\n%s" % (command, len(data), data),
          : append_newline=False)
ERROR root: MetadataException: Metadata Exception: pkg ebuild src:
          : sys-devel/gettext-0.19.4, attr keywords
ERROR root: error: Metadata Exception: pkg ebuild src:
          : sys-devel/gettext-0.19.4, attr data
ERROR root: error: bytes_ro_StringIO instance has no attribute '__len__'

app-text/acroread
  NonExistentDeps: version 9.5.5-r3: depset rdepends: nonexistent atoms [ <x11-libs/pango-1.31 ]

app-text/adiff
  DeprecatedEAPI: version 1.4: uses deprecated EAPI: 0

app-text/agrep
  DeprecatedEAPI: version 2.04: uses deprecated EAPI: 0
  DeprecatedEAPI: version 2.04-r1: uses deprecated EAPI: 0

app-text/aiksaurus
  DeprecatedEAPI: version 1.2.1: uses deprecated EAPI: 2

app-text/antixls
  DeprecatedEAPI: version 0.3b: uses deprecated EAPI: 0

app-text/asciidoc
  DeprecatedEclass: version 8.6.5: uses deprecated eclass(es): [ python (migrate to python-r1 / python-single-r1 / python-any-r1) ]
  DeprecatedEAPI: version 8.6.5: uses deprecated EAPI: 3
  NonExistentDeps: version 8.6.5: depset depends: nonexistent atoms [ =dev-lang/python-2.5* ]
  NonExistentDeps: version 8.6.5: depset rdepends: nonexistent atoms [ =dev-lang/python-2.5* ]
ERROR pkgcore: caught unexpected exception accessing keywords from ebuild src:
             : sys-devel/gettext-0.19.4, exception Metadata Exception: pkg
             : ebuild src: sys-devel/gettext-0.19.4, attr keywords
ERROR pkgcore: error: Metadata Exception: pkg ebuild src:
             : sys-devel/gettext-0.19.4, attr data
ERROR pkgcore: error: bytes_ro_StringIO instance has no attribute '__len__'
ERROR pkgcore: None
ERROR root: check <pkgcheck.visibility.VisibilityReport object at
          : 0x7f4e389710d0> raised
ERROR root: Traceback (most recent call last):
ERROR root:   File "/usr/lib64/python2.7/site-packages/pkgcheck/base.py", line
          : 337, in feed
ERROR root:     check.feed(item, reporter)
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcheck/visibility.py", line
          : 264, in feed
ERROR root:     self.process_depset(pkg, attr, edepset, profiles, reporter)
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcheck/visibility.py", line
          : 315, in process_depset
ERROR root:     if any(True for pkg in src if visible(pkg)):
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcheck/visibility.py", line
          : 315, in <genexpr>
ERROR root:     if any(True for pkg in src if visible(pkg)):
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/restrictions/boolean.py
          : ", line 247, in match
ERROR root:     if not rest.match(vals):
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/package/base.py", line
          : 101, in dynamic_getattr_dict
ERROR root:     raise_from(MetadataException(self, attr, str(e)))
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/package/base.py", line
          : 93, in dynamic_getattr_dict
ERROR root:     val = functor(self)
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/ebuild/ebuild_src.py",
          : line 207, in <lambda>
ERROR root:     s.data.pop("KEYWORDS", "").split()))
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/package/base.py", line
          : 103, in dynamic_getattr_dict
ERROR root:     raise_from(MetadataException(self, attr, str(e)))
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/package/base.py", line
          : 93, in dynamic_getattr_dict
ERROR root:     val = functor(self)
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/package/metadata.py",
          : line 59, in _get_data
ERROR root:     return self._fetch_metadata()
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/ebuild/ebuild_src.py",
          : line 274, in _fetch_metadata
ERROR root:     return self._parent._get_metadata(self, ebp=ebp,
          : force_regen=force_regen)
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/ebuild/ebuild_src.py",
          : line 365, in _get_metadata
ERROR root:     return self._update_metadata(pkg, ebp=ebp)
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/ebuild/ebuild_src.py",
          : line 373, in _update_metadata
ERROR root:     mydata = my_proc.get_keys(pkg, self._ecache)
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/ebuild/processor.py",
          : line 835, in get_keys
ERROR root:     {"key": receive_key})
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/ebuild/processor.py",
          : line 768, in _run_depend_like_phase
ERROR root:     self.write("%s %i\n%s" % (command, len(data), data),
          : append_newline=False)
ERROR root: MetadataException: Metadata Exception: pkg ebuild src:
          : sys-devel/gettext-0.19.4, attr keywords
ERROR root: error: Metadata Exception: pkg ebuild src:
          : sys-devel/gettext-0.19.4, attr data
ERROR root: error: bytes_ro_StringIO instance has no attribute '__len__'
ERROR pkgcore: caught unexpected exception accessing keywords from ebuild src:
             : sys-devel/gettext-0.19.4, exception Metadata Exception: pkg
             : ebuild src: sys-devel/gettext-0.19.4, attr keywords
ERROR pkgcore: error: Metadata Exception: pkg ebuild src:
             : sys-devel/gettext-0.19.4, attr data
ERROR pkgcore: error: bytes_ro_StringIO instance has no attribute '__len__'
ERROR pkgcore: None
ERROR root: check <pkgcheck.visibility.VisibilityReport object at
          : 0x7f4e389710d0> raised
ERROR root: Traceback (most recent call last):
ERROR root:   File "/usr/lib64/python2.7/site-packages/pkgcheck/base.py", line
          : 337, in feed
ERROR root:     check.feed(item, reporter)
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcheck/visibility.py", line
          : 264, in feed
ERROR root:     self.process_depset(pkg, attr, edepset, profiles, reporter)
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcheck/visibility.py", line
          : 315, in process_depset
ERROR root:     if any(True for pkg in src if visible(pkg)):
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcheck/visibility.py", line
          : 315, in <genexpr>
ERROR root:     if any(True for pkg in src if visible(pkg)):
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/restrictions/boolean.py
          : ", line 247, in match
ERROR root:     if not rest.match(vals):
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/package/base.py", line
          : 101, in dynamic_getattr_dict
ERROR root:     raise_from(MetadataException(self, attr, str(e)))
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/package/base.py", line
          : 93, in dynamic_getattr_dict
ERROR root:     val = functor(self)
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/ebuild/ebuild_src.py",
          : line 207, in <lambda>
ERROR root:     s.data.pop("KEYWORDS", "").split()))
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/package/base.py", line
          : 103, in dynamic_getattr_dict
ERROR root:     raise_from(MetadataException(self, attr, str(e)))
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/package/base.py", line
          : 93, in dynamic_getattr_dict
ERROR root:     val = functor(self)
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/package/metadata.py",
          : line 59, in _get_data
ERROR root:     return self._fetch_metadata()
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/ebuild/ebuild_src.py",
          : line 274, in _fetch_metadata
ERROR root:     return self._parent._get_metadata(self, ebp=ebp,
          : force_regen=force_regen)
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/ebuild/ebuild_src.py",
          : line 365, in _get_metadata
ERROR root:     return self._update_metadata(pkg, ebp=ebp)
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/ebuild/ebuild_src.py",
          : line 373, in _update_metadata
ERROR root:     mydata = my_proc.get_keys(pkg, self._ecache)
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/ebuild/processor.py",
          : line 835, in get_keys
ERROR root:     {"key": receive_key})
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/ebuild/processor.py",
          : line 768, in _run_depend_like_phase
ERROR root:     self.write("%s %i\n%s" % (command, len(data), data),
          : append_newline=False)
ERROR root: MetadataException: Metadata Exception: pkg ebuild src:
          : sys-devel/gettext-0.19.4, attr keywords
ERROR root: error: Metadata Exception: pkg ebuild src:
          : sys-devel/gettext-0.19.4, attr data
ERROR root: error: bytes_ro_StringIO instance has no attribute '__len__'
ERROR pkgcore: caught unexpected exception accessing keywords from ebuild src:
             : sys-devel/gettext-0.19.4, exception Metadata Exception: pkg
             : ebuild src: sys-devel/gettext-0.19.4, attr keywords
ERROR pkgcore: error: Metadata Exception: pkg ebuild src:
             : sys-devel/gettext-0.19.4, attr data
ERROR pkgcore: error: bytes_ro_StringIO instance has no attribute '__len__'
ERROR pkgcore: None
ERROR root: check <pkgcheck.visibility.VisibilityReport object at
          : 0x7f4e389710d0> raised
ERROR root: Traceback (most recent call last):
ERROR root:   File "/usr/lib64/python2.7/site-packages/pkgcheck/base.py", line
          : 337, in feed
ERROR root:     check.feed(item, reporter)
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcheck/visibility.py", line
          : 264, in feed
ERROR root:     self.process_depset(pkg, attr, edepset, profiles, reporter)
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcheck/visibility.py", line
          : 315, in process_depset
ERROR root:     if any(True for pkg in src if visible(pkg)):
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcheck/visibility.py", line
          : 315, in <genexpr>
ERROR root:     if any(True for pkg in src if visible(pkg)):
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/restrictions/boolean.py
          : ", line 247, in match
ERROR root:     if not rest.match(vals):
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/package/base.py", line
          : 101, in dynamic_getattr_dict
ERROR root:     raise_from(MetadataException(self, attr, str(e)))
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/package/base.py", line
          : 93, in dynamic_getattr_dict
ERROR root:     val = functor(self)
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/ebuild/ebuild_src.py",
          : line 207, in <lambda>
ERROR root:     s.data.pop("KEYWORDS", "").split()))
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/package/base.py", line
          : 103, in dynamic_getattr_dict
ERROR root:     raise_from(MetadataException(self, attr, str(e)))
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/package/base.py", line
          : 93, in dynamic_getattr_dict
ERROR root:     val = functor(self)
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/package/metadata.py",
          : line 59, in _get_data
ERROR root:     return self._fetch_metadata()
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/ebuild/ebuild_src.py",
          : line 274, in _fetch_metadata
ERROR root:     return self._parent._get_metadata(self, ebp=ebp,
          : force_regen=force_regen)
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/ebuild/ebuild_src.py",
          : line 365, in _get_metadata
ERROR root:     return self._update_metadata(pkg, ebp=ebp)
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/ebuild/ebuild_src.py",
          : line 373, in _update_metadata
ERROR root:     mydata = my_proc.get_keys(pkg, self._ecache)
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/ebuild/processor.py",
          : line 835, in get_keys
ERROR root:     {"key": receive_key})
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/ebuild/processor.py",
          : line 768, in _run_depend_like_phase
ERROR root:     self.write("%s %i\n%s" % (command, len(data), data),
          : append_newline=False)
ERROR root: MetadataException: Metadata Exception: pkg ebuild src:
          : sys-devel/gettext-0.19.4, attr keywords
ERROR root: error: Metadata Exception: pkg ebuild src:
          : sys-devel/gettext-0.19.4, attr data
ERROR root: error: bytes_ro_StringIO instance has no attribute '__len__'
ERROR pkgcore: caught unexpected exception accessing keywords from ebuild src:
             : sys-devel/gettext-0.19.4, exception Metadata Exception: pkg
             : ebuild src: sys-devel/gettext-0.19.4, attr keywords
ERROR pkgcore: error: Metadata Exception: pkg ebuild src:
             : sys-devel/gettext-0.19.4, attr data
ERROR pkgcore: error: bytes_ro_StringIO instance has no attribute '__len__'
ERROR pkgcore: None
ERROR root: check <pkgcheck.visibility.VisibilityReport object at
          : 0x7f4e389710d0> raised
ERROR root: Traceback (most recent call last):
ERROR root:   File "/usr/lib64/python2.7/site-packages/pkgcheck/base.py", line
          : 337, in feed
ERROR root:     check.feed(item, reporter)
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcheck/visibility.py", line
          : 264, in feed
ERROR root:     self.process_depset(pkg, attr, edepset, profiles, reporter)
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcheck/visibility.py", line
          : 315, in process_depset
ERROR root:     if any(True for pkg in src if visible(pkg)):
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcheck/visibility.py", line
          : 315, in <genexpr>
ERROR root:     if any(True for pkg in src if visible(pkg)):
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/restrictions/boolean.py
          : ", line 247, in match
ERROR root:     if not rest.match(vals):
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/package/base.py", line
          : 101, in dynamic_getattr_dict
ERROR root:     raise_from(MetadataException(self, attr, str(e)))
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/package/base.py", line
          : 93, in dynamic_getattr_dict
ERROR root:     val = functor(self)
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/ebuild/ebuild_src.py",
          : line 207, in <lambda>
ERROR root:     s.data.pop("KEYWORDS", "").split()))
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/package/base.py", line
          : 103, in dynamic_getattr_dict
ERROR root:     raise_from(MetadataException(self, attr, str(e)))
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/package/base.py", line
          : 93, in dynamic_getattr_dict
ERROR root:     val = functor(self)
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/package/metadata.py",
          : line 59, in _get_data
ERROR root:     return self._fetch_metadata()
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/ebuild/ebuild_src.py",
          : line 274, in _fetch_metadata
ERROR root:     return self._parent._get_metadata(self, ebp=ebp,
          : force_regen=force_regen)
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/ebuild/ebuild_src.py",
          : line 365, in _get_metadata
ERROR root:     return self._update_metadata(pkg, ebp=ebp)
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/ebuild/ebuild_src.py",
          : line 373, in _update_metadata
ERROR root:     mydata = my_proc.get_keys(pkg, self._ecache)
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/ebuild/processor.py",
          : line 835, in get_keys
ERROR root:     {"key": receive_key})
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/ebuild/processor.py",
          : line 768, in _run_depend_like_phase
ERROR root:     self.write("%s %i\n%s" % (command, len(data), data),
          : append_newline=False)
ERROR root: MetadataException: Metadata Exception: pkg ebuild src:
          : sys-devel/gettext-0.19.4, attr keywords
ERROR root: error: Metadata Exception: pkg ebuild src:
          : sys-devel/gettext-0.19.4, attr data
ERROR root: error: bytes_ro_StringIO instance has no attribute '__len__'

app-text/bibclean
  DeprecatedEAPI: version 2.11.4: uses deprecated EAPI: 0

app-text/bibletime
  DroppedKeywordWarning: version 2.10.1: keywords dropped: ppc

app-text/bibus
  DeprecatedEclass: version 1.5.1: uses deprecated eclass(es): [ python (migrate to python-r1 / python-single-r1 / python-any-r1) ]
  DeprecatedEAPI: version 1.5.1: uses deprecated EAPI: 3
  DeprecatedEclass: version 1.5.2: uses deprecated eclass(es): [ python (migrate to python-r1 / python-single-r1 / python-any-r1) ]

app-text/bibutils
  DeprecatedEAPI: version 4.12: uses deprecated EAPI: 2

app-text/binfind
  DeprecatedEAPI: version 0.0.3: uses deprecated EAPI: 0

app-text/chm2pdf
  DeprecatedEclass: version 0.9.1-r1: uses deprecated eclass(es): [ python (migrate to python-r1 / python-single-r1 / python-any-r1) ]
  DeprecatedEAPI: version 0.9.1-r1: uses deprecated EAPI: 2
  NonExistentDeps: version 0.9.1-r1: depset rdepends: nonexistent atoms [ <dev-libs/chmlib-0.40-r1 ]

app-text/clara
  DeprecatedEAPI: version 20031214: uses deprecated EAPI: 0

app-text/cmigemo
  DeprecatedEAPI: version 1.3c: uses deprecated EAPI: 0
  DeprecatedEAPI: version 1.3c-r1: uses deprecated EAPI: 2
  DeprecatedEAPI: version 1.3c-r2: uses deprecated EAPI: 2
  NonExistentDeps: version 1.3c-r2: depset depends: nonexistent atoms [ net-misc/fetch ]

app-text/code2html
  DeprecatedEAPI: version 0.9.1-r1: uses deprecated EAPI: 3

app-text/convertlit
  DeprecatedEAPI: version 1.8-r1: uses deprecated EAPI: 0

app-text/convmv
  DeprecatedEAPI: version 1.15: uses deprecated EAPI: 3

app-text/cook
  WhitespaceFound: version 1.0.2-r1: ebuild has leading whitespace on lines 35, 37
  DeprecatedEAPI: version 1.0.2-r1: uses deprecated EAPI: 0

app-text/crf++
  DeprecatedEAPI: version 0.54: uses deprecated EAPI: 3
  DeprecatedEAPI: version 0.58: uses deprecated EAPI: 3

app-text/crm114
  DeprecatedEAPI: version 20100106: uses deprecated EAPI: 2

app-text/cwtext
  DeprecatedEAPI: version 0.96: uses deprecated EAPI: 0

app-text/ddir
  DeprecatedEAPI: version 0_p20100323: uses deprecated EAPI: 0
ERROR pkgcore: caught unexpected exception accessing keywords from ebuild src:
             : sys-devel/gettext-0.19.4, exception Metadata Exception: pkg
             : ebuild src: sys-devel/gettext-0.19.4, attr keywords
ERROR pkgcore: error: Metadata Exception: pkg ebuild src:
             : sys-devel/gettext-0.19.4, attr data
ERROR pkgcore: error: bytes_ro_StringIO instance has no attribute '__len__'
ERROR pkgcore: None
ERROR root: check <pkgcheck.visibility.VisibilityReport object at
          : 0x7f4e389710d0> raised
ERROR root: Traceback (most recent call last):
ERROR root:   File "/usr/lib64/python2.7/site-packages/pkgcheck/base.py", line
          : 337, in feed
ERROR root:     check.feed(item, reporter)
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcheck/visibility.py", line
          : 264, in feed
ERROR root:     self.process_depset(pkg, attr, edepset, profiles, reporter)
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcheck/visibility.py", line
          : 315, in process_depset
ERROR root:     if any(True for pkg in src if visible(pkg)):
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcheck/visibility.py", line
          : 315, in <genexpr>
ERROR root:     if any(True for pkg in src if visible(pkg)):
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/restrictions/boolean.py
          : ", line 247, in match
ERROR root:     if not rest.match(vals):
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/package/base.py", line
          : 101, in dynamic_getattr_dict
ERROR root:     raise_from(MetadataException(self, attr, str(e)))
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/package/base.py", line
          : 93, in dynamic_getattr_dict
ERROR root:     val = functor(self)
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/ebuild/ebuild_src.py",
          : line 207, in <lambda>
ERROR root:     s.data.pop("KEYWORDS", "").split()))
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/package/base.py", line
          : 103, in dynamic_getattr_dict
ERROR root:     raise_from(MetadataException(self, attr, str(e)))
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/package/base.py", line
          : 93, in dynamic_getattr_dict
ERROR root:     val = functor(self)
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/package/metadata.py",
          : line 59, in _get_data
ERROR root:     return self._fetch_metadata()
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/ebuild/ebuild_src.py",
          : line 274, in _fetch_metadata
ERROR root:     return self._parent._get_metadata(self, ebp=ebp,
          : force_regen=force_regen)
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/ebuild/ebuild_src.py",
          : line 365, in _get_metadata
ERROR root:     return self._update_metadata(pkg, ebp=ebp)
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/ebuild/ebuild_src.py",
          : line 373, in _update_metadata
ERROR root:     mydata = my_proc.get_keys(pkg, self._ecache)
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/ebuild/processor.py",
          : line 835, in get_keys
ERROR root:     {"key": receive_key})
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/ebuild/processor.py",
          : line 768, in _run_depend_like_phase
ERROR root:     self.write("%s %i\n%s" % (command, len(data), data),
          : append_newline=False)
ERROR root: MetadataException: Metadata Exception: pkg ebuild src:
          : sys-devel/gettext-0.19.4, attr keywords
ERROR root: error: Metadata Exception: pkg ebuild src:
          : sys-devel/gettext-0.19.4, attr data
ERROR root: error: bytes_ro_StringIO instance has no attribute '__len__'

app-text/ding
  DeprecatedEAPI: version 1.7: uses deprecated EAPI: 3

app-text/docbook-dsssl-stylesheets
  DeprecatedEAPI: version 1.79: uses deprecated EAPI: 3

app-text/docbook-sgml
  DeprecatedEAPI: version 1.0: uses deprecated EAPI: 0

app-text/docbook-sgml-dtd
  DeprecatedEAPI: version 3.0-r3: uses deprecated EAPI: 0
  DeprecatedEAPI: version 3.1-r3: uses deprecated EAPI: 0
  DeprecatedEAPI: version 4.0-r3: uses deprecated EAPI: 0
  DeprecatedEAPI: version 4.1-r3: uses deprecated EAPI: 0
  DeprecatedEAPI: version 4.2-r2: uses deprecated EAPI: 0
  DeprecatedEAPI: version 4.3-r2: uses deprecated EAPI: 0
  DeprecatedEAPI: version 4.4: uses deprecated EAPI: 0
  DeprecatedEAPI: version 4.5: uses deprecated EAPI: 0

app-text/docbook-sgml-utils
  DeprecatedEAPI: version 0.6.14-r1: uses deprecated EAPI: 3

app-text/docbook-xml-dtd
  DeprecatedEAPI: version 4.1.2-r6: uses deprecated EAPI: 0
  DeprecatedEAPI: version 4.2-r2: uses deprecated EAPI: 0
  DeprecatedEAPI: version 4.3-r1: uses deprecated EAPI: 0
  DeprecatedEAPI: version 4.4-r2: uses deprecated EAPI: 0
  DeprecatedEAPI: version 4.5-r1: uses deprecated EAPI: 0

app-text/docbook-xml-simple-dtd
  DeprecatedEAPI: version 1.0-r1: uses deprecated EAPI: 0
  DeprecatedEAPI: version 1.0-r2: uses deprecated EAPI: 0
  DeprecatedEAPI: version 4.1.2.4-r2: uses deprecated EAPI: 0
  DeprecatedEAPI: version 4.1.2.4-r3: uses deprecated EAPI: 0
  DeprecatedEAPI: version 4.1.2.5-r2: uses deprecated EAPI: 0
ERROR pkgcore: caught unexpected exception accessing keywords from ebuild src:
             : sys-devel/gettext-0.19.4, exception Metadata Exception: pkg
             : ebuild src: sys-devel/gettext-0.19.4, attr keywords
ERROR pkgcore: error: Metadata Exception: pkg ebuild src:
             : sys-devel/gettext-0.19.4, attr data
ERROR pkgcore: error: bytes_ro_StringIO instance has no attribute '__len__'
ERROR pkgcore: None
ERROR root: check <pkgcheck.visibility.VisibilityReport object at
          : 0x7f4e389710d0> raised
ERROR root: Traceback (most recent call last):
ERROR root:   File "/usr/lib64/python2.7/site-packages/pkgcheck/base.py", line
          : 337, in feed
ERROR root:     check.feed(item, reporter)
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcheck/visibility.py", line
          : 264, in feed
ERROR root:     self.process_depset(pkg, attr, edepset, profiles, reporter)
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcheck/visibility.py", line
          : 315, in process_depset
ERROR root:     if any(True for pkg in src if visible(pkg)):
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcheck/visibility.py", line
          : 315, in <genexpr>
ERROR root:     if any(True for pkg in src if visible(pkg)):
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/restrictions/boolean.py
          : ", line 247, in match
ERROR root:     if not rest.match(vals):
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/package/base.py", line
          : 101, in dynamic_getattr_dict
ERROR root:     raise_from(MetadataException(self, attr, str(e)))
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/package/base.py", line
          : 93, in dynamic_getattr_dict
ERROR root:     val = functor(self)
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/ebuild/ebuild_src.py",
          : line 207, in <lambda>
ERROR root:     s.data.pop("KEYWORDS", "").split()))
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/package/base.py", line
          : 103, in dynamic_getattr_dict
ERROR root:     raise_from(MetadataException(self, attr, str(e)))
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/package/base.py", line
          : 93, in dynamic_getattr_dict
ERROR root:     val = functor(self)
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/package/metadata.py",
          : line 59, in _get_data
ERROR root:     return self._fetch_metadata()
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/ebuild/ebuild_src.py",
          : line 274, in _fetch_metadata
ERROR root:     return self._parent._get_metadata(self, ebp=ebp,
          : force_regen=force_regen)
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/ebuild/ebuild_src.py",
          : line 365, in _get_metadata
ERROR root:     return self._update_metadata(pkg, ebp=ebp)
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/ebuild/ebuild_src.py",
          : line 373, in _update_metadata
ERROR root:     mydata = my_proc.get_keys(pkg, self._ecache)
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/ebuild/processor.py",
          : line 835, in get_keys
ERROR root:     {"key": receive_key})
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/ebuild/processor.py",
          : line 768, in _run_depend_like_phase
ERROR root:     self.write("%s %i\n%s" % (command, len(data), data),
          : append_newline=False)
ERROR root: MetadataException: Metadata Exception: pkg ebuild src:
          : sys-devel/gettext-0.19.4, attr keywords
ERROR root: error: Metadata Exception: pkg ebuild src:
          : sys-devel/gettext-0.19.4, attr data
ERROR root: error: bytes_ro_StringIO instance has no attribute '__len__'
ERROR pkgcore: caught unexpected exception accessing keywords from ebuild src:
             : sys-devel/gettext-0.19.4, exception Metadata Exception: pkg
             : ebuild src: sys-devel/gettext-0.19.4, attr keywords
ERROR pkgcore: error: Metadata Exception: pkg ebuild src:
             : sys-devel/gettext-0.19.4, attr data
ERROR pkgcore: error: bytes_ro_StringIO instance has no attribute '__len__'
ERROR pkgcore: None
ERROR root: check <pkgcheck.visibility.VisibilityReport object at
          : 0x7f4e389710d0> raised
ERROR root: Traceback (most recent call last):
ERROR root:   File "/usr/lib64/python2.7/site-packages/pkgcheck/base.py", line
          : 337, in feed
ERROR root:     check.feed(item, reporter)
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcheck/visibility.py", line
          : 264, in feed
ERROR root:     self.process_depset(pkg, attr, edepset, profiles, reporter)
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcheck/visibility.py", line
          : 315, in process_depset
ERROR root:     if any(True for pkg in src if visible(pkg)):
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcheck/visibility.py", line
          : 315, in <genexpr>
ERROR root:     if any(True for pkg in src if visible(pkg)):
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/restrictions/boolean.py
          : ", line 247, in match
ERROR root:     if not rest.match(vals):
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/package/base.py", line
          : 101, in dynamic_getattr_dict
ERROR root:     raise_from(MetadataException(self, attr, str(e)))
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/package/base.py", line
          : 93, in dynamic_getattr_dict
ERROR root:     val = functor(self)
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/ebuild/ebuild_src.py",
          : line 207, in <lambda>
ERROR root:     s.data.pop("KEYWORDS", "").split()))
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/package/base.py", line
          : 103, in dynamic_getattr_dict
ERROR root:     raise_from(MetadataException(self, attr, str(e)))
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/package/base.py", line
          : 93, in dynamic_getattr_dict
ERROR root:     val = functor(self)
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/package/metadata.py",
          : line 59, in _get_data
ERROR root:     return self._fetch_metadata()
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/ebuild/ebuild_src.py",
          : line 274, in _fetch_metadata
ERROR root:     return self._parent._get_metadata(self, ebp=ebp,
          : force_regen=force_regen)
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/ebuild/ebuild_src.py",
          : line 365, in _get_metadata
ERROR root:     return self._update_metadata(pkg, ebp=ebp)
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/ebuild/ebuild_src.py",
          : line 373, in _update_metadata
ERROR root:     mydata = my_proc.get_keys(pkg, self._ecache)
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/ebuild/processor.py",
          : line 835, in get_keys
ERROR root:     {"key": receive_key})
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/ebuild/processor.py",
          : line 768, in _run_depend_like_phase
ERROR root:     self.write("%s %i\n%s" % (command, len(data), data),
          : append_newline=False)
ERROR root: MetadataException: Metadata Exception: pkg ebuild src:
          : sys-devel/gettext-0.19.4, attr keywords
ERROR root: error: Metadata Exception: pkg ebuild src:
          : sys-devel/gettext-0.19.4, attr data
ERROR root: error: bytes_ro_StringIO instance has no attribute '__len__'
ERROR pkgcore: caught unexpected exception accessing keywords from ebuild src:
             : sys-devel/gettext-0.19.4, exception Metadata Exception: pkg
             : ebuild src: sys-devel/gettext-0.19.4, attr keywords
ERROR pkgcore: error: Metadata Exception: pkg ebuild src:
             : sys-devel/gettext-0.19.4, attr data
ERROR pkgcore: error: bytes_ro_StringIO instance has no attribute '__len__'
ERROR pkgcore: None
ERROR root: check <pkgcheck.visibility.VisibilityReport object at
          : 0x7f4e389710d0> raised
ERROR root: Traceback (most recent call last):
ERROR root:   File "/usr/lib64/python2.7/site-packages/pkgcheck/base.py", line
          : 337, in feed
ERROR root:     check.feed(item, reporter)
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcheck/visibility.py", line
          : 264, in feed
ERROR root:     self.process_depset(pkg, attr, edepset, profiles, reporter)
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcheck/visibility.py", line
          : 315, in process_depset
ERROR root:     if any(True for pkg in src if visible(pkg)):
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcheck/visibility.py", line
          : 315, in <genexpr>
ERROR root:     if any(True for pkg in src if visible(pkg)):
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/restrictions/boolean.py
          : ", line 247, in match
ERROR root:     if not rest.match(vals):
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/package/base.py", line
          : 101, in dynamic_getattr_dict
ERROR root:     raise_from(MetadataException(self, attr, str(e)))
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/package/base.py", line
          : 93, in dynamic_getattr_dict
ERROR root:     val = functor(self)
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/ebuild/ebuild_src.py",
          : line 207, in <lambda>
ERROR root:     s.data.pop("KEYWORDS", "").split()))
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/package/base.py", line
          : 103, in dynamic_getattr_dict
ERROR root:     raise_from(MetadataException(self, attr, str(e)))
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/package/base.py", line
          : 93, in dynamic_getattr_dict
ERROR root:     val = functor(self)
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/package/metadata.py",
          : line 59, in _get_data
ERROR root:     return self._fetch_metadata()
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/ebuild/ebuild_src.py",
          : line 274, in _fetch_metadata
ERROR root:     return self._parent._get_metadata(self, ebp=ebp,
          : force_regen=force_regen)
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/ebuild/ebuild_src.py",
          : line 365, in _get_metadata
ERROR root:     return self._update_metadata(pkg, ebp=ebp)
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/ebuild/ebuild_src.py",
          : line 373, in _update_metadata
ERROR root:     mydata = my_proc.get_keys(pkg, self._ecache)
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/ebuild/processor.py",
          : line 835, in get_keys
ERROR root:     {"key": receive_key})
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/ebuild/processor.py",
          : line 768, in _run_depend_like_phase
ERROR root:     self.write("%s %i\n%s" % (command, len(data), data),
          : append_newline=False)
ERROR root: MetadataException: Metadata Exception: pkg ebuild src:
          : sys-devel/gettext-0.19.4, attr keywords
ERROR root: error: Metadata Exception: pkg ebuild src:
          : sys-devel/gettext-0.19.4, attr data
ERROR root: error: bytes_ro_StringIO instance has no attribute '__len__'

app-text/duali
  DeprecatedEclass: version 0.2.0: uses deprecated eclass(es): [ python (migrate to python-r1 / python-single-r1 / python-any-r1) ]
  DeprecatedEAPI: version 0.2.0: uses deprecated EAPI: 3

app-text/dvibook
  DeprecatedEAPI: version 20001129: uses deprecated EAPI: 0

app-text/dvipdfm
  DeprecatedEAPI: version 0.13.2d-r1: uses deprecated EAPI: 3
  DeprecatedEAPI: version 0.13.2d-r2: uses deprecated EAPI: 3

app-text/dvipdfmx
  DeprecatedEAPI: version 20110311-r1: uses deprecated EAPI: 3

app-text/dvipsk
  DroppedKeywordWarning: version 5.994_p20140525: keywords dropped: ia64, sparc

app-text/enscript
  DeprecatedEAPI: version 1.6.6: uses deprecated EAPI: 2
ERROR pkgcore: caught unexpected exception accessing keywords from ebuild src:
             : sys-devel/gettext-0.19.4, exception Metadata Exception: pkg
             : ebuild src: sys-devel/gettext-0.19.4, attr keywords
ERROR pkgcore: error: Metadata Exception: pkg ebuild src:
             : sys-devel/gettext-0.19.4, attr data
ERROR pkgcore: error: bytes_ro_StringIO instance has no attribute '__len__'
ERROR pkgcore: None
ERROR root: check <pkgcheck.visibility.VisibilityReport object at
          : 0x7f4e389710d0> raised
ERROR root: Traceback (most recent call last):
ERROR root:   File "/usr/lib64/python2.7/site-packages/pkgcheck/base.py", line
          : 337, in feed
ERROR root:     check.feed(item, reporter)
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcheck/visibility.py", line
          : 264, in feed
ERROR root:     self.process_depset(pkg, attr, edepset, profiles, reporter)
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcheck/visibility.py", line
          : 315, in process_depset
ERROR root:     if any(True for pkg in src if visible(pkg)):
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcheck/visibility.py", line
          : 315, in <genexpr>
ERROR root:     if any(True for pkg in src if visible(pkg)):
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/restrictions/boolean.py
          : ", line 247, in match
ERROR root:     if not rest.match(vals):
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/package/base.py", line
          : 101, in dynamic_getattr_dict
ERROR root:     raise_from(MetadataException(self, attr, str(e)))
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/package/base.py", line
          : 93, in dynamic_getattr_dict
ERROR root:     val = functor(self)
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/ebuild/ebuild_src.py",
          : line 207, in <lambda>
ERROR root:     s.data.pop("KEYWORDS", "").split()))
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/package/base.py", line
          : 103, in dynamic_getattr_dict
ERROR root:     raise_from(MetadataException(self, attr, str(e)))
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/package/base.py", line
          : 93, in dynamic_getattr_dict
ERROR root:     val = functor(self)
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/package/metadata.py",
          : line 59, in _get_data
ERROR root:     return self._fetch_metadata()
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/ebuild/ebuild_src.py",
          : line 274, in _fetch_metadata
ERROR root:     return self._parent._get_metadata(self, ebp=ebp,
          : force_regen=force_regen)
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/ebuild/ebuild_src.py",
          : line 365, in _get_metadata
ERROR root:     return self._update_metadata(pkg, ebp=ebp)
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/ebuild/ebuild_src.py",
          : line 373, in _update_metadata
ERROR root:     mydata = my_proc.get_keys(pkg, self._ecache)
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/ebuild/processor.py",
          : line 835, in get_keys
ERROR root:     {"key": receive_key})
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/ebuild/processor.py",
          : line 768, in _run_depend_like_phase
ERROR root:     self.write("%s %i\n%s" % (command, len(data), data),
          : append_newline=False)
ERROR root: MetadataException: Metadata Exception: pkg ebuild src:
          : sys-devel/gettext-0.19.4, attr keywords
ERROR root: error: Metadata Exception: pkg ebuild src:
          : sys-devel/gettext-0.19.4, attr data
ERROR root: error: bytes_ro_StringIO instance has no attribute '__len__'
ERROR pkgcore: caught unexpected exception accessing keywords from ebuild src:
             : sys-devel/gettext-0.19.4, exception Metadata Exception: pkg
             : ebuild src: sys-devel/gettext-0.19.4, attr keywords
ERROR pkgcore: error: Metadata Exception: pkg ebuild src:
             : sys-devel/gettext-0.19.4, attr data
ERROR pkgcore: error: bytes_ro_StringIO instance has no attribute '__len__'
ERROR pkgcore: None
ERROR root: check <pkgcheck.visibility.VisibilityReport object at
          : 0x7f4e389710d0> raised
ERROR root: Traceback (most recent call last):
ERROR root:   File "/usr/lib64/python2.7/site-packages/pkgcheck/base.py", line
          : 337, in feed
ERROR root:     check.feed(item, reporter)
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcheck/visibility.py", line
          : 264, in feed
ERROR root:     self.process_depset(pkg, attr, edepset, profiles, reporter)
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcheck/visibility.py", line
          : 315, in process_depset
ERROR root:     if any(True for pkg in src if visible(pkg)):
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcheck/visibility.py", line
          : 315, in <genexpr>
ERROR root:     if any(True for pkg in src if visible(pkg)):
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/restrictions/boolean.py
          : ", line 247, in match
ERROR root:     if not rest.match(vals):
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/package/base.py", line
          : 101, in dynamic_getattr_dict
ERROR root:     raise_from(MetadataException(self, attr, str(e)))
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/package/base.py", line
          : 93, in dynamic_getattr_dict
ERROR root:     val = functor(self)
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/ebuild/ebuild_src.py",
          : line 207, in <lambda>
ERROR root:     s.data.pop("KEYWORDS", "").split()))
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/package/base.py", line
          : 103, in dynamic_getattr_dict
ERROR root:     raise_from(MetadataException(self, attr, str(e)))
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/package/base.py", line
          : 93, in dynamic_getattr_dict
ERROR root:     val = functor(self)
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/package/metadata.py",
          : line 59, in _get_data
ERROR root:     return self._fetch_metadata()
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/ebuild/ebuild_src.py",
          : line 274, in _fetch_metadata
ERROR root:     return self._parent._get_metadata(self, ebp=ebp,
          : force_regen=force_regen)
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/ebuild/ebuild_src.py",
          : line 365, in _get_metadata
ERROR root:     return self._update_metadata(pkg, ebp=ebp)
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/ebuild/ebuild_src.py",
          : line 373, in _update_metadata
ERROR root:     mydata = my_proc.get_keys(pkg, self._ecache)
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/ebuild/processor.py",
          : line 835, in get_keys
ERROR root:     {"key": receive_key})
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/ebuild/processor.py",
          : line 768, in _run_depend_like_phase
ERROR root:     self.write("%s %i\n%s" % (command, len(data), data),
          : append_newline=False)
ERROR root: MetadataException: Metadata Exception: pkg ebuild src:
          : sys-devel/gettext-0.19.4, attr keywords
ERROR root: error: Metadata Exception: pkg ebuild src:
          : sys-devel/gettext-0.19.4, attr data
ERROR root: error: bytes_ro_StringIO instance has no attribute '__len__'
ERROR pkgcore: caught unexpected exception accessing keywords from ebuild src:
             : sys-devel/gettext-0.19.4, exception Metadata Exception: pkg
             : ebuild src: sys-devel/gettext-0.19.4, attr keywords
ERROR pkgcore: error: Metadata Exception: pkg ebuild src:
             : sys-devel/gettext-0.19.4, attr data
ERROR pkgcore: error: bytes_ro_StringIO instance has no attribute '__len__'
ERROR pkgcore: None
ERROR root: check <pkgcheck.visibility.VisibilityReport object at
          : 0x7f4e389710d0> raised
ERROR root: Traceback (most recent call last):
ERROR root:   File "/usr/lib64/python2.7/site-packages/pkgcheck/base.py", line
          : 337, in feed
ERROR root:     check.feed(item, reporter)
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcheck/visibility.py", line
          : 264, in feed
ERROR root:     self.process_depset(pkg, attr, edepset, profiles, reporter)
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcheck/visibility.py", line
          : 315, in process_depset
ERROR root:     if any(True for pkg in src if visible(pkg)):
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcheck/visibility.py", line
          : 315, in <genexpr>
ERROR root:     if any(True for pkg in src if visible(pkg)):
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/restrictions/boolean.py
          : ", line 247, in match
ERROR root:     if not rest.match(vals):
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/package/base.py", line
          : 101, in dynamic_getattr_dict
ERROR root:     raise_from(MetadataException(self, attr, str(e)))
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/package/base.py", line
          : 93, in dynamic_getattr_dict
ERROR root:     val = functor(self)
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/ebuild/ebuild_src.py",
          : line 207, in <lambda>
ERROR root:     s.data.pop("KEYWORDS", "").split()))
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/package/base.py", line
          : 103, in dynamic_getattr_dict
ERROR root:     raise_from(MetadataException(self, attr, str(e)))
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/package/base.py", line
          : 93, in dynamic_getattr_dict
ERROR root:     val = functor(self)
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/package/metadata.py",
          : line 59, in _get_data
ERROR root:     return self._fetch_metadata()
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/ebuild/ebuild_src.py",
          : line 274, in _fetch_metadata
ERROR root:     return self._parent._get_metadata(self, ebp=ebp,
          : force_regen=force_regen)
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/ebuild/ebuild_src.py",
          : line 365, in _get_metadata
ERROR root:     return self._update_metadata(pkg, ebp=ebp)
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/ebuild/ebuild_src.py",
          : line 373, in _update_metadata
ERROR root:     mydata = my_proc.get_keys(pkg, self._ecache)
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/ebuild/processor.py",
          : line 835, in get_keys
ERROR root:     {"key": receive_key})
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/ebuild/processor.py",
          : line 768, in _run_depend_like_phase
ERROR root:     self.write("%s %i\n%s" % (command, len(data), data),
          : append_newline=False)
ERROR root: MetadataException: Metadata Exception: pkg ebuild src:
          : sys-devel/gettext-0.19.4, attr keywords
ERROR root: error: Metadata Exception: pkg ebuild src:
          : sys-devel/gettext-0.19.4, attr data
ERROR root: error: bytes_ro_StringIO instance has no attribute '__len__'

app-text/fbless
  DeprecatedEclass: version 9999: uses deprecated eclass(es): [ git-2 (migrate to git-r3) ]

app-text/fdftk
  DeprecatedEAPI: version 6.0-r1: uses deprecated EAPI: 0
  MissingChksum: version 6.0-r1: "FDFToolkitForUnix.tar.gz" missing required chksums: sha512, whirlpool; has chksums: sha256, size

app-text/freepwing
  DeprecatedEAPI: version 1.4.3: uses deprecated EAPI: 0

app-text/gentoo-guide-xml-dtd
  DeprecatedEAPI: version 2.1-r1: uses deprecated EAPI: 0
ERROR pkgcore: caught unexpected exception accessing keywords from ebuild src:
             : sys-devel/gettext-0.19.4, exception Metadata Exception: pkg
             : ebuild src: sys-devel/gettext-0.19.4, attr keywords
ERROR pkgcore: error: Metadata Exception: pkg ebuild src:
             : sys-devel/gettext-0.19.4, attr data
ERROR pkgcore: error: bytes_ro_StringIO instance has no attribute '__len__'
ERROR pkgcore: None
ERROR root: check <pkgcheck.visibility.VisibilityReport object at
          : 0x7f4e389710d0> raised
ERROR root: Traceback (most recent call last):
ERROR root:   File "/usr/lib64/python2.7/site-packages/pkgcheck/base.py", line
          : 337, in feed
ERROR root:     check.feed(item, reporter)
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcheck/visibility.py", line
          : 264, in feed
ERROR root:     self.process_depset(pkg, attr, edepset, profiles, reporter)
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcheck/visibility.py", line
          : 315, in process_depset
ERROR root:     if any(True for pkg in src if visible(pkg)):
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcheck/visibility.py", line
          : 315, in <genexpr>
ERROR root:     if any(True for pkg in src if visible(pkg)):
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/restrictions/boolean.py
          : ", line 247, in match
ERROR root:     if not rest.match(vals):
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/package/base.py", line
          : 101, in dynamic_getattr_dict
ERROR root:     raise_from(MetadataException(self, attr, str(e)))
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/package/base.py", line
          : 93, in dynamic_getattr_dict
ERROR root:     val = functor(self)
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/ebuild/ebuild_src.py",
          : line 207, in <lambda>
ERROR root:     s.data.pop("KEYWORDS", "").split()))
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/package/base.py", line
          : 103, in dynamic_getattr_dict
ERROR root:     raise_from(MetadataException(self, attr, str(e)))
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/package/base.py", line
          : 93, in dynamic_getattr_dict
ERROR root:     val = functor(self)
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/package/metadata.py",
          : line 59, in _get_data
ERROR root:     return self._fetch_metadata()
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/ebuild/ebuild_src.py",
          : line 274, in _fetch_metadata
ERROR root:     return self._parent._get_metadata(self, ebp=ebp,
          : force_regen=force_regen)
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/ebuild/ebuild_src.py",
          : line 365, in _get_metadata
ERROR root:     return self._update_metadata(pkg, ebp=ebp)
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/ebuild/ebuild_src.py",
          : line 373, in _update_metadata
ERROR root:     mydata = my_proc.get_keys(pkg, self._ecache)
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/ebuild/processor.py",
          : line 835, in get_keys
ERROR root:     {"key": receive_key})
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/ebuild/processor.py",
          : line 768, in _run_depend_like_phase
ERROR root:     self.write("%s %i\n%s" % (command, len(data), data),
          : append_newline=False)
ERROR root: MetadataException: Metadata Exception: pkg ebuild src:
          : sys-devel/gettext-0.19.4, attr keywords
ERROR root: error: Metadata Exception: pkg ebuild src:
          : sys-devel/gettext-0.19.4, attr data
ERROR root: error: bytes_ro_StringIO instance has no attribute '__len__'
ERROR pkgcore: caught unexpected exception accessing keywords from ebuild src:
             : sys-devel/gettext-0.19.4, exception Metadata Exception: pkg
             : ebuild src: sys-devel/gettext-0.19.4, attr keywords
ERROR pkgcore: error: Metadata Exception: pkg ebuild src:
             : sys-devel/gettext-0.19.4, attr data
ERROR pkgcore: error: bytes_ro_StringIO instance has no attribute '__len__'
ERROR pkgcore: None
ERROR root: check <pkgcheck.visibility.VisibilityReport object at
          : 0x7f4e389710d0> raised
ERROR root: Traceback (most recent call last):
ERROR root:   File "/usr/lib64/python2.7/site-packages/pkgcheck/base.py", line
          : 337, in feed
ERROR root:     check.feed(item, reporter)
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcheck/visibility.py", line
          : 264, in feed
ERROR root:     self.process_depset(pkg, attr, edepset, profiles, reporter)
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcheck/visibility.py", line
          : 315, in process_depset
ERROR root:     if any(True for pkg in src if visible(pkg)):
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcheck/visibility.py", line
          : 315, in <genexpr>
ERROR root:     if any(True for pkg in src if visible(pkg)):
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/restrictions/boolean.py
          : ", line 247, in match
ERROR root:     if not rest.match(vals):
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/package/base.py", line
          : 101, in dynamic_getattr_dict
ERROR root:     raise_from(MetadataException(self, attr, str(e)))
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/package/base.py", line
          : 93, in dynamic_getattr_dict
ERROR root:     val = functor(self)
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/ebuild/ebuild_src.py",
          : line 207, in <lambda>
ERROR root:     s.data.pop("KEYWORDS", "").split()))
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/package/base.py", line
          : 103, in dynamic_getattr_dict
ERROR root:     raise_from(MetadataException(self, attr, str(e)))
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/package/base.py", line
          : 93, in dynamic_getattr_dict
ERROR root:     val = functor(self)
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/package/metadata.py",
          : line 59, in _get_data
ERROR root:     return self._fetch_metadata()
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/ebuild/ebuild_src.py",
          : line 274, in _fetch_metadata
ERROR root:     return self._parent._get_metadata(self, ebp=ebp,
          : force_regen=force_regen)
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/ebuild/ebuild_src.py",
          : line 365, in _get_metadata
ERROR root:     return self._update_metadata(pkg, ebp=ebp)
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/ebuild/ebuild_src.py",
          : line 373, in _update_metadata
ERROR root:     mydata = my_proc.get_keys(pkg, self._ecache)
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/ebuild/processor.py",
          : line 835, in get_keys
ERROR root:     {"key": receive_key})
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/ebuild/processor.py",
          : line 768, in _run_depend_like_phase
ERROR root:     self.write("%s %i\n%s" % (command, len(data), data),
          : append_newline=False)
ERROR root: MetadataException: Metadata Exception: pkg ebuild src:
          : sys-devel/gettext-0.19.4, attr keywords
ERROR root: error: Metadata Exception: pkg ebuild src:
          : sys-devel/gettext-0.19.4, attr data
ERROR root: error: bytes_ro_StringIO instance has no attribute '__len__'

app-text/gnopaster
  DeprecatedEAPI: version 0.0.9: uses deprecated EAPI: 0

app-text/gtranslator
  NonExistentDeps: version 2.91.6: depset depends: nonexistent atoms [ =gnome-extra/gnome-utils-3.2* ]
  NonExistentDeps: version 2.91.6: depset rdepends: nonexistent atoms [ =gnome-extra/gnome-utils-3.2* ]
ERROR pkgcore: caught unexpected exception accessing keywords from ebuild src:
             : sys-devel/gettext-0.19.4, exception Metadata Exception: pkg
             : ebuild src: sys-devel/gettext-0.19.4, attr keywords
ERROR pkgcore: error: Metadata Exception: pkg ebuild src:
             : sys-devel/gettext-0.19.4, attr data
ERROR pkgcore: error: bytes_ro_StringIO instance has no attribute '__len__'
ERROR pkgcore: None
ERROR root: check <pkgcheck.visibility.VisibilityReport object at
          : 0x7f4e389710d0> raised
ERROR root: Traceback (most recent call last):
ERROR root:   File "/usr/lib64/python2.7/site-packages/pkgcheck/base.py", line
          : 337, in feed
ERROR root:     check.feed(item, reporter)
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcheck/visibility.py", line
          : 264, in feed
ERROR root:     self.process_depset(pkg, attr, edepset, profiles, reporter)
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcheck/visibility.py", line
          : 315, in process_depset
ERROR root:     if any(True for pkg in src if visible(pkg)):
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcheck/visibility.py", line
          : 315, in <genexpr>
ERROR root:     if any(True for pkg in src if visible(pkg)):
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/restrictions/boolean.py
          : ", line 247, in match
ERROR root:     if not rest.match(vals):
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/package/base.py", line
          : 101, in dynamic_getattr_dict
ERROR root:     raise_from(MetadataException(self, attr, str(e)))
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/package/base.py", line
          : 93, in dynamic_getattr_dict
ERROR root:     val = functor(self)
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/ebuild/ebuild_src.py",
          : line 207, in <lambda>
ERROR root:     s.data.pop("KEYWORDS", "").split()))
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/package/base.py", line
          : 103, in dynamic_getattr_dict
ERROR root:     raise_from(MetadataException(self, attr, str(e)))
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/package/base.py", line
          : 93, in dynamic_getattr_dict
ERROR root:     val = functor(self)
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/package/metadata.py",
          : line 59, in _get_data
ERROR root:     return self._fetch_metadata()
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/ebuild/ebuild_src.py",
          : line 274, in _fetch_metadata
ERROR root:     return self._parent._get_metadata(self, ebp=ebp,
          : force_regen=force_regen)
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/ebuild/ebuild_src.py",
          : line 365, in _get_metadata
ERROR root:     return self._update_metadata(pkg, ebp=ebp)
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/ebuild/ebuild_src.py",
          : line 373, in _update_metadata
ERROR root:     mydata = my_proc.get_keys(pkg, self._ecache)
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/ebuild/processor.py",
          : line 835, in get_keys
ERROR root:     {"key": receive_key})
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/ebuild/processor.py",
          : line 768, in _run_depend_like_phase
ERROR root:     self.write("%s %i\n%s" % (command, len(data), data),
          : append_newline=False)
ERROR root: MetadataException: Metadata Exception: pkg ebuild src:
          : sys-devel/gettext-0.19.4, attr keywords
ERROR root: error: Metadata Exception: pkg ebuild src:
          : sys-devel/gettext-0.19.4, attr data
ERROR root: error: bytes_ro_StringIO instance has no attribute '__len__'
ERROR pkgcore: caught unexpected exception accessing keywords from ebuild src:
             : sys-devel/gettext-0.19.4, exception Metadata Exception: pkg
             : ebuild src: sys-devel/gettext-0.19.4, attr keywords
ERROR pkgcore: error: Metadata Exception: pkg ebuild src:
             : sys-devel/gettext-0.19.4, attr data
ERROR pkgcore: error: bytes_ro_StringIO instance has no attribute '__len__'
ERROR pkgcore: None
ERROR root: check <pkgcheck.visibility.VisibilityReport object at
          : 0x7f4e389710d0> raised
ERROR root: Traceback (most recent call last):
ERROR root:   File "/usr/lib64/python2.7/site-packages/pkgcheck/base.py", line
          : 337, in feed
ERROR root:     check.feed(item, reporter)
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcheck/visibility.py", line
          : 264, in feed
ERROR root:     self.process_depset(pkg, attr, edepset, profiles, reporter)
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcheck/visibility.py", line
          : 315, in process_depset
ERROR root:     if any(True for pkg in src if visible(pkg)):
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcheck/visibility.py", line
          : 315, in <genexpr>
ERROR root:     if any(True for pkg in src if visible(pkg)):
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/restrictions/boolean.py
          : ", line 247, in match
ERROR root:     if not rest.match(vals):
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/package/base.py", line
          : 101, in dynamic_getattr_dict
ERROR root:     raise_from(MetadataException(self, attr, str(e)))
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/package/base.py", line
          : 93, in dynamic_getattr_dict
ERROR root:     val = functor(self)
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/ebuild/ebuild_src.py",
          : line 207, in <lambda>
ERROR root:     s.data.pop("KEYWORDS", "").split()))
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/package/base.py", line
          : 103, in dynamic_getattr_dict
ERROR root:     raise_from(MetadataException(self, attr, str(e)))
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/package/base.py", line
          : 93, in dynamic_getattr_dict
ERROR root:     val = functor(self)
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/package/metadata.py",
          : line 59, in _get_data
ERROR root:     return self._fetch_metadata()
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/ebuild/ebuild_src.py",
          : line 274, in _fetch_metadata
ERROR root:     return self._parent._get_metadata(self, ebp=ebp,
          : force_regen=force_regen)
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/ebuild/ebuild_src.py",
          : line 365, in _get_metadata
ERROR root:     return self._update_metadata(pkg, ebp=ebp)
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/ebuild/ebuild_src.py",
          : line 373, in _update_metadata
ERROR root:     mydata = my_proc.get_keys(pkg, self._ecache)
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/ebuild/processor.py",
          : line 835, in get_keys
ERROR root:     {"key": receive_key})
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/ebuild/processor.py",
          : line 768, in _run_depend_like_phase
ERROR root:     self.write("%s %i\n%s" % (command, len(data), data),
          : append_newline=False)
ERROR root: MetadataException: Metadata Exception: pkg ebuild src:
          : sys-devel/gettext-0.19.4, attr keywords
ERROR root: error: Metadata Exception: pkg ebuild src:
          : sys-devel/gettext-0.19.4, attr data
ERROR root: error: bytes_ro_StringIO instance has no attribute '__len__'

app-text/html401
  DeprecatedEAPI: version 19991224-r2: uses deprecated EAPI: 3

app-text/htmlinc
  DeprecatedEAPI: version 1.0_beta1: uses deprecated EAPI: 0
ERROR pkgcore: caught unexpected exception accessing keywords from ebuild src:
             : sys-devel/gettext-0.19.4, exception Metadata Exception: pkg
             : ebuild src: sys-devel/gettext-0.19.4, attr keywords
ERROR pkgcore: error: Metadata Exception: pkg ebuild src:
             : sys-devel/gettext-0.19.4, attr data
ERROR pkgcore: error: bytes_ro_StringIO instance has no attribute '__len__'
ERROR pkgcore: None
ERROR root: check <pkgcheck.visibility.VisibilityReport object at
          : 0x7f4e389710d0> raised
ERROR root: Traceback (most recent call last):
ERROR root:   File "/usr/lib64/python2.7/site-packages/pkgcheck/base.py", line
          : 337, in feed
ERROR root:     check.feed(item, reporter)
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcheck/visibility.py", line
          : 264, in feed
ERROR root:     self.process_depset(pkg, attr, edepset, profiles, reporter)
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcheck/visibility.py", line
          : 315, in process_depset
ERROR root:     if any(True for pkg in src if visible(pkg)):
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcheck/visibility.py", line
          : 315, in <genexpr>
ERROR root:     if any(True for pkg in src if visible(pkg)):
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/restrictions/boolean.py
          : ", line 247, in match
ERROR root:     if not rest.match(vals):
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/package/base.py", line
          : 101, in dynamic_getattr_dict
ERROR root:     raise_from(MetadataException(self, attr, str(e)))
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/package/base.py", line
          : 93, in dynamic_getattr_dict
ERROR root:     val = functor(self)
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/ebuild/ebuild_src.py",
          : line 207, in <lambda>
ERROR root:     s.data.pop("KEYWORDS", "").split()))
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/package/base.py", line
          : 103, in dynamic_getattr_dict
ERROR root:     raise_from(MetadataException(self, attr, str(e)))
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/package/base.py", line
          : 93, in dynamic_getattr_dict
ERROR root:     val = functor(self)
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/package/metadata.py",
          : line 59, in _get_data
ERROR root:     return self._fetch_metadata()
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/ebuild/ebuild_src.py",
          : line 274, in _fetch_metadata
ERROR root:     return self._parent._get_metadata(self, ebp=ebp,
          : force_regen=force_regen)
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/ebuild/ebuild_src.py",
          : line 365, in _get_metadata
ERROR root:     return self._update_metadata(pkg, ebp=ebp)
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/ebuild/ebuild_src.py",
          : line 373, in _update_metadata
ERROR root:     mydata = my_proc.get_keys(pkg, self._ecache)
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/ebuild/processor.py",
          : line 835, in get_keys
ERROR root:     {"key": receive_key})
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/ebuild/processor.py",
          : line 768, in _run_depend_like_phase
ERROR root:     self.write("%s %i\n%s" % (command, len(data), data),
          : append_newline=False)
ERROR root: MetadataException: Metadata Exception: pkg ebuild src:
          : sys-devel/gettext-0.19.4, attr keywords
ERROR root: error: Metadata Exception: pkg ebuild src:
          : sys-devel/gettext-0.19.4, attr data
ERROR root: error: bytes_ro_StringIO instance has no attribute '__len__'

app-text/hyperestraier
  DeprecatedEAPI: version 1.4.13: uses deprecated EAPI: 0

app-text/info2html
  DeprecatedEAPI: version 2.0: uses deprecated EAPI: 0
ERROR pkgcore: caught unexpected exception accessing keywords from ebuild src:
             : sys-devel/gettext-0.19.4, exception Metadata Exception: pkg
             : ebuild src: sys-devel/gettext-0.19.4, attr keywords
ERROR pkgcore: error: Metadata Exception: pkg ebuild src:
             : sys-devel/gettext-0.19.4, attr data
ERROR pkgcore: error: bytes_ro_StringIO instance has no attribute '__len__'
ERROR pkgcore: None
ERROR root: check <pkgcheck.visibility.VisibilityReport object at
          : 0x7f4e389710d0> raised
ERROR root: Traceback (most recent call last):
ERROR root:   File "/usr/lib64/python2.7/site-packages/pkgcheck/base.py", line
          : 337, in feed
ERROR root:     check.feed(item, reporter)
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcheck/visibility.py", line
          : 264, in feed
ERROR root:     self.process_depset(pkg, attr, edepset, profiles, reporter)
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcheck/visibility.py", line
          : 315, in process_depset
ERROR root:     if any(True for pkg in src if visible(pkg)):
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcheck/visibility.py", line
          : 315, in <genexpr>
ERROR root:     if any(True for pkg in src if visible(pkg)):
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/restrictions/boolean.py
          : ", line 247, in match
ERROR root:     if not rest.match(vals):
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/package/base.py", line
          : 101, in dynamic_getattr_dict
ERROR root:     raise_from(MetadataException(self, attr, str(e)))
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/package/base.py", line
          : 93, in dynamic_getattr_dict
ERROR root:     val = functor(self)
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/ebuild/ebuild_src.py",
          : line 207, in <lambda>
ERROR root:     s.data.pop("KEYWORDS", "").split()))
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/package/base.py", line
          : 103, in dynamic_getattr_dict
ERROR root:     raise_from(MetadataException(self, attr, str(e)))
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/package/base.py", line
          : 93, in dynamic_getattr_dict
ERROR root:     val = functor(self)
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/package/metadata.py",
          : line 59, in _get_data
ERROR root:     return self._fetch_metadata()
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/ebuild/ebuild_src.py",
          : line 274, in _fetch_metadata
ERROR root:     return self._parent._get_metadata(self, ebp=ebp,
          : force_regen=force_regen)
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/ebuild/ebuild_src.py",
          : line 365, in _get_metadata
ERROR root:     return self._update_metadata(pkg, ebp=ebp)
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/ebuild/ebuild_src.py",
          : line 373, in _update_metadata
ERROR root:     mydata = my_proc.get_keys(pkg, self._ecache)
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/ebuild/processor.py",
          : line 835, in get_keys
ERROR root:     {"key": receive_key})
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/ebuild/processor.py",
          : line 768, in _run_depend_like_phase
ERROR root:     self.write("%s %i\n%s" % (command, len(data), data),
          : append_newline=False)
ERROR root: MetadataException: Metadata Exception: pkg ebuild src:
          : sys-devel/gettext-0.19.4, attr keywords
ERROR root: error: Metadata Exception: pkg ebuild src:
          : sys-devel/gettext-0.19.4, attr data
ERROR root: error: bytes_ro_StringIO instance has no attribute '__len__'
ERROR pkgcore: caught unexpected exception accessing keywords from ebuild src:
             : sys-devel/gettext-0.19.4, exception Metadata Exception: pkg
             : ebuild src: sys-devel/gettext-0.19.4, attr keywords
ERROR pkgcore: error: Metadata Exception: pkg ebuild src:
             : sys-devel/gettext-0.19.4, attr data
ERROR pkgcore: error: bytes_ro_StringIO instance has no attribute '__len__'
ERROR pkgcore: None
ERROR root: check <pkgcheck.visibility.VisibilityReport object at
          : 0x7f4e389710d0> raised
ERROR root: Traceback (most recent call last):
ERROR root:   File "/usr/lib64/python2.7/site-packages/pkgcheck/base.py", line
          : 337, in feed
ERROR root:     check.feed(item, reporter)
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcheck/visibility.py", line
          : 264, in feed
ERROR root:     self.process_depset(pkg, attr, edepset, profiles, reporter)
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcheck/visibility.py", line
          : 315, in process_depset
ERROR root:     if any(True for pkg in src if visible(pkg)):
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcheck/visibility.py", line
          : 315, in <genexpr>
ERROR root:     if any(True for pkg in src if visible(pkg)):
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/restrictions/boolean.py
          : ", line 247, in match
ERROR root:     if not rest.match(vals):
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/package/base.py", line
          : 101, in dynamic_getattr_dict
ERROR root:     raise_from(MetadataException(self, attr, str(e)))
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/package/base.py", line
          : 93, in dynamic_getattr_dict
ERROR root:     val = functor(self)
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/ebuild/ebuild_src.py",
          : line 207, in <lambda>
ERROR root:     s.data.pop("KEYWORDS", "").split()))
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/package/base.py", line
          : 103, in dynamic_getattr_dict
ERROR root:     raise_from(MetadataException(self, attr, str(e)))
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/package/base.py", line
          : 93, in dynamic_getattr_dict
ERROR root:     val = functor(self)
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/package/metadata.py",
          : line 59, in _get_data
ERROR root:     return self._fetch_metadata()
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/ebuild/ebuild_src.py",
          : line 274, in _fetch_metadata
ERROR root:     return self._parent._get_metadata(self, ebp=ebp,
          : force_regen=force_regen)
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/ebuild/ebuild_src.py",
          : line 365, in _get_metadata
ERROR root:     return self._update_metadata(pkg, ebp=ebp)
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/ebuild/ebuild_src.py",
          : line 373, in _update_metadata
ERROR root:     mydata = my_proc.get_keys(pkg, self._ecache)
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/ebuild/processor.py",
          : line 835, in get_keys
ERROR root:     {"key": receive_key})
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/ebuild/processor.py",
          : line 768, in _run_depend_like_phase
ERROR root:     self.write("%s %i\n%s" % (command, len(data), data),
          : append_newline=False)
ERROR root: MetadataException: Metadata Exception: pkg ebuild src:
          : sys-devel/gettext-0.19.4, attr keywords
ERROR root: error: Metadata Exception: pkg ebuild src:
          : sys-devel/gettext-0.19.4, attr data
ERROR root: error: bytes_ro_StringIO instance has no attribute '__len__'

app-text/jmupdf
  DeprecatedEclass: version 9999: uses deprecated eclass(es): [ git-2 (migrate to git-r3) ]

app-text/landslide
  DeprecatedEclass: version 1.1.1: uses deprecated eclass(es): [ distutils (migrate to distutils-r1), python (migrate to python-r1 / python-single-r1 / python-any-r1) ]
  DeprecatedEAPI: version 1.1.1: uses deprecated EAPI: 3

app-text/lcdf-typetools
  DeprecatedEAPI: version 2.97: uses deprecated EAPI: 2
  DeprecatedEAPI: version 2.98: uses deprecated EAPI: 2
  DeprecatedEAPI: version 2.99: uses deprecated EAPI: 2
  DeprecatedEAPI: version 2.100: uses deprecated EAPI: 2
  DeprecatedEAPI: version 2.104: uses deprecated EAPI: 2

app-text/libabw
  DroppedKeywordWarning: version 0.1.0: keywords dropped: ppc

app-text/libebook
  DroppedKeywordWarning: version 0.1.1: keywords dropped: ppc, ppc64

app-text/libetonyek
  DeprecatedEclass: version 9999: uses deprecated eclass(es): [ git-2 (migrate to git-r3) ]
  DroppedKeywordWarning: version 0.1.1: keywords dropped: ppc
ERROR pkgcore: caught unexpected exception accessing keywords from ebuild src:
             : sys-devel/gettext-0.19.4, exception Metadata Exception: pkg
             : ebuild src: sys-devel/gettext-0.19.4, attr keywords
ERROR pkgcore: error: Metadata Exception: pkg ebuild src:
             : sys-devel/gettext-0.19.4, attr data
ERROR pkgcore: error: bytes_ro_StringIO instance has no attribute '__len__'
ERROR pkgcore: None
ERROR root: check <pkgcheck.visibility.VisibilityReport object at
          : 0x7f4e389710d0> raised
ERROR root: Traceback (most recent call last):
ERROR root:   File "/usr/lib64/python2.7/site-packages/pkgcheck/base.py", line
          : 337, in feed
ERROR root:     check.feed(item, reporter)
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcheck/visibility.py", line
          : 264, in feed
ERROR root:     self.process_depset(pkg, attr, edepset, profiles, reporter)
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcheck/visibility.py", line
          : 315, in process_depset
ERROR root:     if any(True for pkg in src if visible(pkg)):
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcheck/visibility.py", line
          : 315, in <genexpr>
ERROR root:     if any(True for pkg in src if visible(pkg)):
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/restrictions/boolean.py
          : ", line 247, in match
ERROR root:     if not rest.match(vals):
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/package/base.py", line
          : 101, in dynamic_getattr_dict
ERROR root:     raise_from(MetadataException(self, attr, str(e)))
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/package/base.py", line
          : 93, in dynamic_getattr_dict
ERROR root:     val = functor(self)
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/ebuild/ebuild_src.py",
          : line 207, in <lambda>
ERROR root:     s.data.pop("KEYWORDS", "").split()))
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/package/base.py", line
          : 103, in dynamic_getattr_dict
ERROR root:     raise_from(MetadataException(self, attr, str(e)))
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/package/base.py", line
          : 93, in dynamic_getattr_dict
ERROR root:     val = functor(self)
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/package/metadata.py",
          : line 59, in _get_data
ERROR root:     return self._fetch_metadata()
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/ebuild/ebuild_src.py",
          : line 274, in _fetch_metadata
ERROR root:     return self._parent._get_metadata(self, ebp=ebp,
          : force_regen=force_regen)
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/ebuild/ebuild_src.py",
          : line 365, in _get_metadata
ERROR root:     return self._update_metadata(pkg, ebp=ebp)
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/ebuild/ebuild_src.py",
          : line 373, in _update_metadata
ERROR root:     mydata = my_proc.get_keys(pkg, self._ecache)
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/ebuild/processor.py",
          : line 835, in get_keys
ERROR root:     {"key": receive_key})
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/ebuild/processor.py",
          : line 768, in _run_depend_like_phase
ERROR root:     self.write("%s %i\n%s" % (command, len(data), data),
          : append_newline=False)
ERROR root: MetadataException: Metadata Exception: pkg ebuild src:
          : sys-devel/gettext-0.19.4, attr keywords
ERROR root: error: Metadata Exception: pkg ebuild src:
          : sys-devel/gettext-0.19.4, attr data
ERROR root: error: bytes_ro_StringIO instance has no attribute '__len__'
ERROR pkgcore: caught unexpected exception accessing keywords from ebuild src:
             : sys-devel/gettext-0.19.4, exception Metadata Exception: pkg
             : ebuild src: sys-devel/gettext-0.19.4, attr keywords
ERROR pkgcore: error: Metadata Exception: pkg ebuild src:
             : sys-devel/gettext-0.19.4, attr data
ERROR pkgcore: error: bytes_ro_StringIO instance has no attribute '__len__'
ERROR pkgcore: None
ERROR root: check <pkgcheck.visibility.VisibilityReport object at
          : 0x7f4e389710d0> raised
ERROR root: Traceback (most recent call last):
ERROR root:   File "/usr/lib64/python2.7/site-packages/pkgcheck/base.py", line
          : 337, in feed
ERROR root:     check.feed(item, reporter)
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcheck/visibility.py", line
          : 264, in feed
ERROR root:     self.process_depset(pkg, attr, edepset, profiles, reporter)
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcheck/visibility.py", line
          : 315, in process_depset
ERROR root:     if any(True for pkg in src if visible(pkg)):
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcheck/visibility.py", line
          : 315, in <genexpr>
ERROR root:     if any(True for pkg in src if visible(pkg)):
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/restrictions/boolean.py
          : ", line 247, in match
ERROR root:     if not rest.match(vals):
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/package/base.py", line
          : 101, in dynamic_getattr_dict
ERROR root:     raise_from(MetadataException(self, attr, str(e)))
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/package/base.py", line
          : 93, in dynamic_getattr_dict
ERROR root:     val = functor(self)
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/ebuild/ebuild_src.py",
          : line 207, in <lambda>
ERROR root:     s.data.pop("KEYWORDS", "").split()))
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/package/base.py", line
          : 103, in dynamic_getattr_dict
ERROR root:     raise_from(MetadataException(self, attr, str(e)))
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/package/base.py", line
          : 93, in dynamic_getattr_dict
ERROR root:     val = functor(self)
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/package/metadata.py",
          : line 59, in _get_data
ERROR root:     return self._fetch_metadata()
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/ebuild/ebuild_src.py",
          : line 274, in _fetch_metadata
ERROR root:     return self._parent._get_metadata(self, ebp=ebp,
          : force_regen=force_regen)
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/ebuild/ebuild_src.py",
          : line 365, in _get_metadata
ERROR root:     return self._update_metadata(pkg, ebp=ebp)
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/ebuild/ebuild_src.py",
          : line 373, in _update_metadata
ERROR root:     mydata = my_proc.get_keys(pkg, self._ecache)
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/ebuild/processor.py",
          : line 835, in get_keys
ERROR root:     {"key": receive_key})
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/ebuild/processor.py",
          : line 768, in _run_depend_like_phase
ERROR root:     self.write("%s %i\n%s" % (command, len(data), data),
          : append_newline=False)
ERROR root: MetadataException: Metadata Exception: pkg ebuild src:
          : sys-devel/gettext-0.19.4, attr keywords
ERROR root: error: Metadata Exception: pkg ebuild src:
          : sys-devel/gettext-0.19.4, attr data
ERROR root: error: bytes_ro_StringIO instance has no attribute '__len__'
ERROR pkgcore: caught unexpected exception accessing keywords from ebuild src:
             : sys-devel/gettext-0.19.4, exception Metadata Exception: pkg
             : ebuild src: sys-devel/gettext-0.19.4, attr keywords
ERROR pkgcore: error: Metadata Exception: pkg ebuild src:
             : sys-devel/gettext-0.19.4, attr data
ERROR pkgcore: error: bytes_ro_StringIO instance has no attribute '__len__'
ERROR pkgcore: None
ERROR root: check <pkgcheck.visibility.VisibilityReport object at
          : 0x7f4e389710d0> raised
ERROR root: Traceback (most recent call last):
ERROR root:   File "/usr/lib64/python2.7/site-packages/pkgcheck/base.py", line
          : 337, in feed
ERROR root:     check.feed(item, reporter)
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcheck/visibility.py", line
          : 264, in feed
ERROR root:     self.process_depset(pkg, attr, edepset, profiles, reporter)
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcheck/visibility.py", line
          : 315, in process_depset
ERROR root:     if any(True for pkg in src if visible(pkg)):
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcheck/visibility.py", line
          : 315, in <genexpr>
ERROR root:     if any(True for pkg in src if visible(pkg)):
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/restrictions/boolean.py
          : ", line 247, in match
ERROR root:     if not rest.match(vals):
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/package/base.py", line
          : 101, in dynamic_getattr_dict
ERROR root:     raise_from(MetadataException(self, attr, str(e)))
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/package/base.py", line
          : 93, in dynamic_getattr_dict
ERROR root:     val = functor(self)
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/ebuild/ebuild_src.py",
          : line 207, in <lambda>
ERROR root:     s.data.pop("KEYWORDS", "").split()))
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/package/base.py", line
          : 103, in dynamic_getattr_dict
ERROR root:     raise_from(MetadataException(self, attr, str(e)))
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/package/base.py", line
          : 93, in dynamic_getattr_dict
ERROR root:     val = functor(self)
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/package/metadata.py",
          : line 59, in _get_data
ERROR root:     return self._fetch_metadata()
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/ebuild/ebuild_src.py",
          : line 274, in _fetch_metadata
ERROR root:     return self._parent._get_metadata(self, ebp=ebp,
          : force_regen=force_regen)
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/ebuild/ebuild_src.py",
          : line 365, in _get_metadata
ERROR root:     return self._update_metadata(pkg, ebp=ebp)
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/ebuild/ebuild_src.py",
          : line 373, in _update_metadata
ERROR root:     mydata = my_proc.get_keys(pkg, self._ecache)
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/ebuild/processor.py",
          : line 835, in get_keys
ERROR root:     {"key": receive_key})
ERROR root:   File
          : "/usr/lib64/python2.7/site-packages/pkgcore/ebuild/processor.py",
          : line 768, in _run_depend_like_phase
ERROR root:     self.write("%s %i\n%s" % (command, len(data), data),
          : append_newline=False)
ERROR root: MetadataException: Metadata Exception: pkg ebuild src:
          : sys-devel/gettext-0.19.4, attr keywords
ERROR root: error: Metadata Exception: pkg ebuild src:
          : sys-devel/gettext-0.19.4, attr data
ERROR root: error: bytes_ro_StringIO instance has no attribute '__len__'

app-text/libmspub
  Deprecate